### ISSUE TITLE
Redis connection leak 

### ISSUE THREAD

**Issue by viggin543** [jitsucom/jitsu#1010]
## Description

We have noticed that the more destinations we created the more Redis connection jitsu consume
currently we have ±130 connections per instance for < 100 destinations

After digging into jitsu code found the reason:

`jitsu/server/storages/factory.go:191`
```
func (f *FactoryImpl) Configure(destinationID string, destination config.DestinationConfig) (func(config *Config) (Storage, error), *Config, error) {
...
	if destination.Mode != SynchronousMode {
		eventQueue, err = f.eventsQueueFactory.CreateEventsQueue(destination.Type, destinationID)
		if err != nil {
			return nil, nil, err
		}
	}
```
seems that Jitsu creates a different Redis connection pool ( with a limit of 5K connection ) 
PER DESTINATION !!

we create snowflake async destinations 

## Steps to reproduce

spin up jitsu with many destinations and send events to every destination

## Expected behavior

Jitsu uses a stable number of redis connections regardless of the number of destinations configured

## Actual behavior

Jitsu redis connections consumption grows linearly with every destination configured.

**Comment by absorbb** [comment]
@viggin543 
Apparently number of redis connection indeed scales with number of destinations - each destination hold 1 additional connection per instance. It is hard to do something about it. But it doesn't explain your numbers.

I've noticed that each redis pool can hold up to 100 idle connections. and each jitsu instance uses more that one pool (but not for each destination – `f.eventsQueueFactory.CreateEventsQueue` uses shared pool)
So i reduced max number of idle connections per pool to 10 in [1.44.4](https://github.com/jitsucom/jitsu/releases/tag/v1.44.4) can you please try it?

**Comment by viggin543** [comment]
**Didn't seem to help.**
Redis connections used after upgrading to 1.44.4

 134 jitsu-1
 139 jitsu-2
 139 jitsu-3

we also have user identification disabled

what is the point of having a dedicated connection per destination? 

Redis is single-threaded.
I don't think having a connection per destination will improve Latency or Throughput
On the contrary, many connections consume resources on Jitsu and Redis ( ram, open ports, kernel CPU time maintaining open ports
 
@absorbb

**Comment by absorbb** [comment]
@viggin543 

Streaming destination uses redis lists for events queues and BLPOP operation to read from queues. That is why each streaming destination holds at least one connections.
That is hard to do something about it in the current Jitsu design.
Good news is that the next big version of Jitsu will use Kafka for event queues.

Also you may consider use batch mode where that is applicable.

**Comment by viggin543** [comment]
Hi @absorbb, this is great news! We would be thrilled to be the first ones to give it a try 😎 Also, I've been longing to utilize Kafka for something, so this is exciting 🥳. Thanks for the update!
