### ISSUE TITLE
Prometheus custom endpoint and authorization

### ISSUE THREAD

**Issue by LeoCo** [jitsucom/jitsu#1012]
### Problem

It's great that Jitsu has lots of Prometheus metrics we can leverage but having a non default endpoint under authentication it's a friction to leverage metrics in enterprise environments. Since Jitsu it's using a non default endpoint, we should be able to customise it. Also, using the admin token as a url params it's not really secure, if the http requests are logged then the admin password will be exposed.

### Solution

To address the issue I have prepared a PR #1011

**Comment by absorbb** [comment]
@LeoCo  Thank you for the PR 👍

It went to [1.44.4 release](https://github.com/jitsucom/jitsu/releases/tag/v1.44.4)
