### ISSUE TITLE
Adding GA4 as a Destination

### ISSUE THREAD

**Issue by n-j-o** [jitsucom/jitsu#1013]
### Problem
The current Google Analytics implementation only handles UA type tracking codes, and is therefore incompatible with GA4's latest data streams and Measurement ID. The legacy version of GA which uses a `UA` tag for tracking will be sunsetted from the start of June 2023, meaning any existing Jistu projects would no longer be able to send data to GA as a destination.

### Solution
**Option 1 (preferred) :** Rename the current Google Analytics destination as `Google Analytics (UA / Legacy)` and then create a new Destination for GA4, where `Measurement ID` can be set, in-place of the current `UA` tracking id. By creating a new destination you'll avoid potential conflicts with existing 'live' implementation(s) and also allow for a totally different transformation / mapping schema, given GA4 will undoubtedly allow for different data structures. 

Potential downside with this approach is for users on the 'Free' plan, as they may have a destination limit which causes problem(s) when trying to add the new GA4 destination for testing. Perhaps there could be a ~4 month grace period where the GA4 Destination is not counted towards a user's total destination count?

**Option 2 :** Refactor the existing Google Analytics destination to permit the use of a `Measurement ID` alongside a `Tracking ID` and send tracking events to both, or whichever has a value set.

**Comment by absorbb** [comment]
Hi @n-j-o !

We are going to implement GA4 destination in the upcoming major release of Jitsu: https://docs-jitsu-com.staging.jitsu.com/destinations/ga4

but with caveats:

GA4 uses different protocol and doesn't support fully featured server to server mode that worked with UA measurement protocol.
GA4 requires client tags (gtag, Tag Manager,...) for integration to work properly.

Read more about limitations: https://developers.google.com/analytics/devguides/collection/protocol/ga4#caveats_to_measurement_protocol

With this in mind are you still interested in GA4 destination in Jitsu?

**Comment by jelen07** [comment]
Hi, I'm testing the Google Analytics 4 destination. I've already configured the Postgres destination and it works properly.
But I can't see any events in GA4. Is there any further configuration of GA4?

<img width="1243" alt="Snímek obrazovky 2023-12-07 v 18 39 01" src="https://github.com/jitsucom/jitsu/assets/2346295/6e3fc436-0bce-41f9-955e-0ec2b5a600dd">

<img width="1255" alt="Snímek obrazovky 2023-12-07 v 18 43 12" src="https://github.com/jitsucom/jitsu/assets/2346295/19fa8764-5d57-4b3a-a722-dc9ed0b2987a">

**Comment by vklimontovich** [comment]
@jelen07 it's really hard to tell what's going on without additional details. GA4 should work without additional configuration. Do you see any errors in API Destinations & Functions logs?

**Comment by jelen07** [comment]
I guess that should be enough just to set up the destination and the `p.js` script set up the GA/GTM tag or "some bridge" that sends the events to GA as well as to Postgres. Or should I add the GA4/GTM snippet manually? 🤔 
Like
```html
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-XXX"></script>
      <script type="text/javascript">
          window.dataLayer = window.dataLayer || [];
          function gtag(){ dataLayer.push(arguments); }
          gtag('js', new Date());

          gtag('config', 'G-XXX');
      </script>
```

Where can the errors be found?

<img width="1321" alt="Snímek obrazovky 2023-12-07 v 18 53 13" src="https://github.com/jitsucom/jitsu/assets/2346295/9850ad79-d59e-4c3f-b06c-6d38e0b27989">

<img width="1321" alt="Snímek obrazovky 2023-12-07 v 18 53 09" src="https://github.com/jitsucom/jitsu/assets/2346295/aac64fd5-0abb-49dc-b6d0-507df0bb3b67">

<img width="1321" alt="Snímek obrazovky 2023-12-07 v 18 53 11" src="https://github.com/jitsucom/jitsu/assets/2346295/853a01a5-d44c-4f1c-afa9-c4960e8eb377">
