### ISSUE TITLE
Facebook API Version v17 is not supported

### ISSUE THREAD

**Issue by stormrage-project** [jitsucom/jitsu#1017]
As mentioned in the title. The Facebook API Version V17 is not supported in the latest docker compose installation.

I get this error, when trying to add "Facebook Marketing" as a source:

general: Error ID:f4621b97d6e047449f9c24ba458577b4: facebook: (#2635) Your app has been upgraded to version v17.0, please use this version or newer. This can be verified in the settings tab on the App Dashboard. (code: 2635; error_subcode: 0, error_user_title: , error_user_msg: ) (#400)

**Comment by absorbb** [comment]
Hi @stormrage-project 

Can you please try to set docker-compose to use `beta` image.
E.g. replace `jitsucom/jitsu` image with `jitsucom/jitsu:beta`

**Comment by absorbb** [comment]
@stormrage-project do you use source connector or destination connector?

**Comment by hiroszi** [comment]
> @stormrage-project do you use source connector or destination connector?

source connector

**Comment by absorbb** [comment]
@hiroszi 
Can you please try the latest release: https://github.com/jitsucom/jitsu/releases/tag/v1.44.7
