### ISSUE TITLE
The DockerHub Docker Image Overview for jitsucom/jitsu appears to be out of date

### ISSUE THREAD

**Issue by nelsnelson** [jitsucom/jitsu#1022]
## Environment

    Deploy method: ran from sources -> ./docker-start-console.sh
    Jitsu version: 2
    OS: macos 13.4.1

## Description

Following the instructions at the DockerHub Docker Image Overview for jitsucom/jitsu (https://hub.docker.com/r/jitsucom/jitsu) fails, overview document appears to be out of date.

Trying to run with "./docker-start-console.sh" fails.

### Error:

    nelsnelson@mercurio:~/Documents/workspace/x/jitsu[newjitsu]$ chmod -R 777 compose-data/
    chmod: compose-data/: No such file or directory

### Error:

    nelsnelson@mercurio:~/Documents/workspace/x/jitsu[newjitsu]$ docker-compose up
    no configuration file provided: not found

### Error:

    nelsnelson@mercurio:~/Documents/workspace/x/jitsu[newjitsu]$ ./docker-start-console.sh         
    Starting the app
    Waiting for localhost:3000 to be up...
    
    > root@0.0.0 console:start
    > dotenv -e .env.local -- pnpm run --filter=console console:start
    
    /Users/nelsnelson/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/dotenv-2.7.6/lib/dotenv/cli.rb:34:in `parse_argv!': invalid option: -e (    OptionParser::InvalidOption)
      from /Users/nelsnelson/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/dotenv-2.7.6/lib/dotenv/cli.rb:18:in `run'
      from /Users/nelsnelson/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/dotenv-2.7.6/bin/dotenv:4:in `<top (required)>'
      from /Users/nelsnelson/.asdf/installs/ruby/3.1.4/bin/dotenv:25:in `load'
      from /Users/nelsnelson/.asdf/installs/ruby/3.1.4/bin/dotenv:25:in `<main>'
    /Users/nelsnelson/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/dotenv-2.7.6/lib/dotenv/cli.rb:34:in `parse_argv!': invalid option: e (    OptionParser::InvalidOption)
      from /Users/nelsnelson/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/dotenv-2.7.6/lib/dotenv/cli.rb:18:in `run'
      from /Users/nelsnelson/.asdf/installs/ruby/3.1.4/lib/ruby/gems/3.1.0/gems/dotenv-2.7.6/bin/dotenv:4:in `<top (required)>'
      from /Users/nelsnelson/.asdf/installs/ruby/3.1.4/bin/dotenv:25:in `load'
      from /Users/nelsnelson/.asdf/installs/ruby/3.1.4/bin/dotenv:25:in `<main>'
    Running healthcheck...
    ❌ ❌ ❌ HEALTHCHECK FAILED - 000 from http://localhost:3000/api/healthcheck. Response:
    cat: healthcheck-result: No such file or directory
    
    zsh: killed     ./docker-start-console.sh

## Steps to reproduce

Simply follow the instructions for Quick Start at https://hub.docker.com/r/jitsucom/jitsu.

## Expected behavior

Jitsu runs

My apologies in advance if this is the incorrect place to post this issue.  The Reporting Bugs and Contributing Code section from the DockerHub Docker Image Overview pointed me here.  But perhaps that is also incorrect?  It isn't clear.

**Comment by absorbb** [comment]
Hi @nelsnelson !

We have not updated yet main branch and readme pages to Jitsu 2.0.
If you want to run standalone version of Jitsu 2.0 you can use this doc:
https://docs.jitsu.com/self-hosting/quick-start

**Comment by TorczerA** [comment]
Hi @absorbb 

I tried following the steps from https://docs.jitsu.com/self-hosting/quick-start and facing a similar error.

Here is a snippet of the logs

rotor_1      | 2023-12-08 11:32:25.955Z INFO  [singleton]: ️🚮🚮🚮 prisma disabled by setting DISABLE_SERVICE_prisma 
rotor_1      | 2023-12-08 11:32:26.000Z INFO  [singleton]: ️🚮🚮🚮 pg disabled by setting DISABLE_SERVICE_pg 
rotor_1      | 2023-12-08 11:32:26.179Z INFO  [singleton]: ️⚡️⚡️⚡️ redis connected in 32ms! 
rotor_1      | 2023-12-08 11:32:26.910Z INFO  [singleton]: ️⚡️⚡️⚡️ redisLogger connected in 6ms! 
rotor_1      | body-parser deprecated undefined extended: provide extended option node:internal/modules/cjs/loader:1376:14
rotor_1      | 2023-12-08 11:32:26.947Z INFO  [rotor]: Starting kafka processing 
rotor_1      | listening for signals
rotor_1      | 2023-12-08 11:32:27.121Z INFO  [redis]: Redis @ redis://default:****@redis:6379 - successfully connected 
rotor_1      | 2023-12-08 11:32:27.167Z INFO  [kafka-rotor]: Subscribing to kafka topics:  destination-messages
kafka_1      | [2023-12-08 11:32:27,270] INFO [GroupCoordinator 1001]: Preparing to rebalance group rotor in state PreparingRebalance with old generation 0 (__consumer_offsets-26) (reason: Adding new member kafka-rotor-b840c1c5-8c30-4dfb-a9d9-bfcfe5db6955 with group instance id None) (kafka.coordinator.group.GroupCoordinator)
kafka_1      | [2023-12-08 11:32:27,272] INFO [GroupCoordinator 1001]: Stabilized group rotor generation 1 (__consumer_offsets-26) with 1 members (kafka.coordinator.group.GroupCoordinator)
kafka_1      | [2023-12-08 11:32:27,294] INFO [GroupCoordinator 1001]: Assignment received from leader for group rotor for generation 1. The group has 1 members, 0 of which are static. (kafka.coordinator.group.GroupCoordinator)
rotor_1      | 2023-12-08 11:32:27.309Z INFO  [rotor]: Kafka processing started. Listening for topics destination-messages with group rotor 
rotor_1      | 2023-12-08 11:32:27.331Z INFO  [rotor]: Listening health-checks on port 3401 
console_1    | 
console_1    | > root@0.0.0 console:db-prepare-force
console_1    | > dotenv -e .env.local -- pnpm run --filter=console db:update-schema-force
console_1    | 
console_1    | .                                        |  WARN  Unsupported engine: wanted: {"node":"18.x"} (current: {"node":"v16.20.2","pnpm":"8.7.5"})
console_1    | 
console_1    | > @jitsu-internal/console@0.0.0 db:update-schema-force /app/webapps/console
console_1    | > dotenv -e ../../.env.local -- prisma db push --accept-data-loss
console_1    | 
console_1    | Prisma schema loaded from prisma/schema.prisma
console_1    | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
console_1    | 
console_1    | 🚀  Your database is now in sync with your Prisma schema. Done in 538ms
console_1    | 
console_1    | Running generate... (Use --skip-generate to skip the generators)
console_1    | warn Preview feature "filterJson" is deprecated. The functionality can be used without specifying it as a preview feature.
✔ Generated Zod Schemas (0.5.4) to ./prisma/schema in 3.70s
console_1    | ✔ Generated Prisma Client (4.12.0 | library) to ./../../node_modules/.pnpm/@pris
console_1    | ma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 2.39s
console_1    | 
console_1    | ┌─────────────────────────────────────────────────────────┐
console_1    | │  Update available 4.12.0 -> 5.7.0                       │
console_1    | │                                                         │
console_1    | │  This is a major update - please follow the guide at    │
console_1    | │  https://pris.ly/d/major-version-upgrade                │
console_1    | │                                                         │
console_1    | │  Run the following to update                            │
console_1    | │    npm i --save-dev prisma@latest                       │
console_1    | │    npm i @prisma/client@latest                          │
console_1    | └─────────────────────────────────────────────────────────┘
console_1    | Starting the app
console_1    | Waiting for localhost:3000 to be up...
console_1    | 
console_1    | > root@0.0.0 console:start
console_1    | > dotenv -e .env.local -- pnpm run --filter=console console:start
console_1    | 
console_1    | .                                        |  WARN  Unsupported engine: wanted: {"node":"18.x"} (current: {"node":"v16.20.2","pnpm":"8.7.5"})
console_1    | 
console_1    | > @jitsu-internal/console@0.0.0 console:start /app/webapps/console
console_1    | > next start
console_1    | 
console_1    | Running healthcheck...
console_1    | ❌ ❌ ❌ HEALTHCHECK FAILED - 000 from http://localhost:3000/api/healthcheck. Response:
console_1    | /bin/cat: healthcheck-result: No such file or directory
console_1    | 
console_1    | Killed
console_1    | UPDATE_DB is set, updating database schema...
console_1    | 
console_1    | > root@0.0.0 console:db-prepare-force
console_1    | > dotenv -e .env.local -- pnpm run --filter=console db:update-schema-force
console_1    | 
console_1    | .                                        |  WARN  Unsupported engine: wanted: {"node":"18.x"} (current: {"node":"v16.20.2","pnpm":"8.7.5"})
console_1    | 
console_1    | > @jitsu-internal/console@0.0.0 db:update-schema-force /app/webapps/console
console_1    | > dotenv -e ../../.env.local -- prisma db push --accept-data-loss
console_1    | 
console_1    | Prisma schema loaded from prisma/schema.prisma
console_1    | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
console_1    | 
console_1    | The database is already in sync with the Prisma schema.
console_1    | 
console_1    | Running generate... (Use --skip-generate to skip the generators)
console_1    | warn Preview feature "filterJson" is deprecated. The functionality can be used without specifying it as a preview feature.
✔ Generated Zod Schemas (0.5.4) to ./prisma/schema in 3.57s
console_1    | ✔ Generated Prisma Client (4.12.0 | library) to ./../../node_modules/.pnpm/@pris
console_1    | ma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 2.45s
console_1    | 
console_1    | Starting the app
console_1    | Waiting for localhost:3000 to be up...
console_1    | 
console_1    | > root@0.0.0 console:start
console_1    | > dotenv -e .env.local -- pnpm run --filter=console console:start
console_1    | 
console_1    | .                                        |  WARN  Unsupported engine: wanted: {"node":"18.x"} (current: {"node":"v16.20.2","pnpm":"8.7.5"})
console_1    | 
console_1    | > @jitsu-internal/console@0.0.0 console:start /app/webapps/console
console_1    | > next start
console_1    | 
console_1    | Running healthcheck...
console_1    | ❌ ❌ ❌ HEALTHCHECK FAILED - 000 from http://localhost:3000/api/healthcheck. Response:
console_1    | /bin/cat: healthcheck-result: No such file or directory
console_1    | 
console_1    | Killed
docker_console_1 exited with code 137
console_1    | UPDATE_DB is set, updating database schema...
console_1    | 
console_1    | > root@0.0.0 console:db-prepare-force
console_1    | > dotenv -e .env.local -- pnpm run --filter=console db:update-schema-force
console_1    | 
console_1    | .                                        |  WARN  Unsupported engine: wanted: {"node":"18.x"} (current: {"node":"v16.20.2","pnpm":"8.7.5"})
console_1    | 
console_1    | > @jitsu-internal/console@0.0.0 db:update-schema-force /app/webapps/console
console_1    | > dotenv -e ../../.env.local -- prisma db push --accept-data-loss
console_1    | 
console_1    | Prisma schema loaded from prisma/schema.prisma
console_1    | Datasource "db": PostgreSQL database "postgres", schema "public" at "postgres:5432"
console_1    | 
console_1    | The database is already in sync with the Prisma schema.
console_1    | 
console_1    | Running generate... (Use --skip-generate to skip the generators)
console_1    | warn Preview feature "filterJson" is deprecated. The functionality can be used without specifying it as a preview feature.
✔ Generated Zod Schemas (0.5.4) to ./prisma/schema in 3.72s
console_1    | ✔ Generated Prisma Client (4.12.0 | library) to ./../../node_modules/.pnpm/@pris
console_1    | ma+client@4.12.0_prisma@4.12.0/node_modules/@prisma/client in 2.50s
console_1    | 
console_1    | Starting the app
console_1    | Waiting for localhost:3000 to be up...
console_1    | 
console_1    | > root@0.0.0 console:start
console_1    | > dotenv -e .env.local -- pnpm run --filter=console console:start
console_1    | 
console_1    | .                                        |  WARN  Unsupported engine: wanted: {"node":"18.x"} (current: {"node":"v16.20.2","pnpm":"8.7.5"})
console_1    | 
console_1    | > @jitsu-internal/console@0.0.0 console:start /app/webapps/console
console_1    | > next start
console_1    | 
console_1    | Running healthcheck...
console_1    | ❌ ❌ ❌ HEALTHCHECK FAILED - 000 from http://localhost:3000/api/healthcheck. Response:
console_1    | /bin/cat: healthcheck-result: No such file or directory
console_1    | 
console_1    | Killed
