### ISSUE TITLE
Lost incoming events because Destination was unreachable for hours 

### ISSUE THREAD

**Issue by stouch** [jitsucom/jitsu#1023]
My destination has been unavailable for few hours, and Incoming events were listed but never sent to destination (never appeared in Processed events). 

Once we fixed the destination, the events were not processed neither, so I restarted the pod which host jitsu (but I did not touch to redis because I thought may be there were some failed/delayed jobs).

I waited then, but none of the incoming events were processed after few hours.

So : 
1. What happen to incoming event if destination is unreachable for hours and then re-reachable ?
2. Does restarting the instance which host jitsu (but without restarting redis) has an impact on pending events ?

**Comment by absorbb** [comment]
@stouch 
Jitsu tries to recognize type of destination errors. And if it assumes that it worth to retry a message it stays in redis queue.
In your case it seems that jitsu failed to recognize error type - so it went to 'failed' logs file that by default located in:
`/home/eventnative/data/logs/events/failed` directory inside container.

These files can be manually reprocessed with bulk api endpoint:
https://classic.jitsu.com/docs/sending-data/bulk-api
`fallback` parameter must be set
Endpoint expects payload with `multipart/form-data` content-type.

**Comment by stouch** [comment]
Thank you, 
As I restarted my jitsu pod, it lost all the data inside (I thought only redis was used for cache, my big mistake)...
I'll know this for the next time.
