### ISSUE TITLE
Documentation for Google ADS PERFORMANCE_MAX campaigns

### ISSUE THREAD

**Issue by icychocolate98** [jitsucom/jitsu#1026]
Good morning,

The main purpose of this issue is to propose the implementation of specific documentation for "PERFORMANCE_MAX" campaigns in the Google Ads API.

We encountered a problem while trying to retrieve performance metrics for "PERFORMANCE_MAX" campaigns in the "campaign" stream. After conducting extensive research on various websites.

 I came across a helpful blog post that provided the solution: https://groups.google.com/g/adwords-api/c/_mxbgNckaLQ?pli=1

The blog post mentioned that the Google Ads API supports performance max report data at the campaign level but not at the ad group level or ad level. This insight clarified the issue for us.

> Kindly note that Google Ads API supports performance max report data at campaign level, and not ad group level or ad level.

The problem arose from our initial selection of _**ad**_ and _**ad_group**_ metric fields, which resulted in empty data for "PERFORMANCE_MAX" campaigns. The solution lies in understanding which metrics can be selected for performance max campaigns.

I believe it is crucial to document this implementation since an increasing number of people are using "PERFORMANCE_MAX" campaigns. Having this information readily available will be immensely valuable to users who want to work with performance max campaigns effectively.

I hope this suggestion helps improve the overall documentation and knowledge base for Google Ads API users. 

Thank you for considering it!

**Comment by vklimontovich** [comment]
Seems like it's related to Jitsu Classic, I'm going to close this one unless same issue is reproduceable in Jitsu Next
