### ISSUE TITLE
Validation error at Salesforce Singer form

### ISSUE THREAD

**Issue by antonioorct** [jitsucom/jitsu#1030]
![image](https://github.com/jitsucom/jitsu/assets/14859262/5659f2fc-7792-43d4-894c-4fc171741c1c)

Inserting any value in the following field throws an error:

`Error: type must be JSONType or JSONType[]: number,`

```
> 49 | const validate = ajv.compile(fieldSchema);
     |                     ^
  50 | if (!validate(value)) {
  51 |   //show only one error message for the field
  52 |   return validate.errors?.[0].message;
  ```

**Comment by antonioorct** [comment]
Taking the spec for the Singer connector from Airbyte shows the following:

```json
{
  "quota_percent_total": {
    "type": ["number", "null"],
    "default": null,
    "description": "Determines the maximum allowed API quota percentage the connector is allowed to consume at any time"
 },
  "quota_percent_per_run": {
    "type": ["number", null],
    "default": null,
    "description": "determines the maximum allowed API quota percentage the connector is allowed to consume per sync job"
}
```

The difference in the types can be seen; `quota_percent_total` doesn't throw errors while the `quota_percent_per_run` does

**Comment by antonioorct** [comment]
![image](https://github.com/jitsucom/jitsu/assets/14859262/707e9e21-0b0e-443a-a31d-3e5f80fa1cdd)

A similar validation error also happens with the previous field

**Comment by absorbb** [comment]
@antonioorct 
The problem is fixed in the latest `jitsucom/console` image. Please make sure to pull the fresh one.

Any particular reasons why you prefer the Singer version over the native Airbyte one?

**Comment by antonioorct** [comment]
I saw the native one doesn't offer a nice catalog of objects to choose from when creating the service, instead you have to manually input object name criteria while the Singer connector displays a list of all the objects immediately.
@absorbb
