### ISSUE TITLE
Jitsu adds underscore in front of key values is they start with a capital letter

### ISSUE THREAD

**Issue by acmeguy** [jitsucom/jitsu#1037]
This property value:
[{"Some": "Some"},{"Other": "Other"}],

Becomes:
'[{"_some": "Some"},{"_other": "Other"}]',

I understand that you want to enforce snake_case, but this should really become:
'[{"some": "Some"},{"other": "Other"}]',
if you insist on doing that.

It uses a list instead of a map (for now) to avoid field generation for each new key found.

**Comment by absorbb** [comment]
Fixed for https://use.jitsu.com and in the latest `jitsucom/rotor` image.

Thank you for reporting that.
