### ISSUE TITLE
Detect geo from cloudflare headers

### ISSUE THREAD

**Issue by ScottEAdams** [jitsucom/jitsu#1047]
Similar to #1028 , would be nice to use cloudflare headers when available - https://developers.cloudflare.com/rules/transform/managed-transforms/reference/

cf-ipcity: The visitor's city
cf-ipcountry: The visitor's country 
cf-ipcontinent: The visitor's continent 
cf-iplongitude: The visitor's longitude 
cf-iplatitude: The visitor's latitude
cf-region: The visitor's region
cf-region-code: The visitor's region code 
cf-metro-code: The visitor's metro code 
cf-postal-code: The visitor's postal code 
cf-timezone: The name of the visitor's timezone

**Comment by vklimontovich** [comment]
We won't do it as a part of core jitsu, but you can easily do so with functions, [see `ctx.headers`](https://docs.jitsu.com/functions/#quick-intro)
