### ISSUE TITLE
Robot Crawl Prevention

### ISSUE THREAD

**Issue by hamrio** [jitsucom/jitsu#1048]
For self host jitsu, we need to prevent crawl robot to access our jitsu. For this case we need to block robot access to jitsu index page (welcome page)

These are some options
1. `<meta name="robots" content="noindex" /> `adding meta into jitsu html page (welcome page)
2. adding robot.txt file

Thank you

**Comment by hamrio** [comment]
I still use jitsu classic for now because I still need the Source configuration

**Comment by absorbb** [comment]
@hamrio 
You can use `server.disable_signature: true` yaml or `SERVER_DISABLE_SIGNATURE=true` env parameter and welcome page will become empty. Will it work for you?

**Comment by hamrio** [comment]
@absorbb 
I already use that option and the HTML is empty. but it still created a page which will be crawled by google robot if it hosted in subdomain.
