### ISSUE TITLE
Kafka container is starting - unhealty

### ISSUE THREAD

**Issue by Rosariobosco** [jitsucom/jitsu#1058]
I am running jitsu as a docker-compose file. While I run the docker-compose up, postgres, redis and zookeeper containers are running. Only Kafka container is unhealthy. I am attaching the logs and running containers
![Screenshot 2023-11-02 at 12 04 42 AM](https://github.com/jitsucom/jitsu/assets/108105002/2346df0c-0bee-498d-b449-592abc162776)
![Screenshot 2023-11-02 at 12 11 16 AM](https://github.com/jitsucom/jitsu/assets/108105002/9219cc19-bc56-4442-b44e-6f1c564e67b3)

**Comment by vklimontovich** [comment]
Maybe issue #1063 fixes that as well? I'm going to close this one, feel free to re-open if the issue persists
