### ISSUE TITLE
FB Conversions API Connector

### ISSUE THREAD

**Issue by drojkind** [jitsucom/jitsu#1059]
Was on a self-hosted version of Jitsu Classic, but have moved to the new Cloud Hosted Version.

Was previously using the Facebook Conversions API connector to send events to Facebook. 

Is there a current workaround to send events to Conversions API using functions? Or a webhook?

**Comment by vklimontovich** [comment]
Not yet, but we can implement facebook connector. So far the workaround will be using [Functions](https://docs.jitsu.com/features/functions/) and make `fetch()` requests to FB api
