### ISSUE TITLE
Source not found error

### ISSUE THREAD

**Issue by teenwolf99** [jitsucom/jitsu#1065]
We are running jitsu via docker-compose file following the quick start guide. Once everything is setup and running we are able to get the data via HTTP API using the curl command.

But we are not getting any data when integrating to the site in jitsu. We are getting below error message,

   **"error": "Source not found for {\"ingestType\":\"browser\",\"domain\":\"example.com\"}"**

Below is the docker file used,

version: "3.8"
services:
  redis:
    tty: true
    image: redis:6.2-alpine
    restart: "unless-stopped"
    ports:
      - "${REDIS_PORT:-6378}:6379"
    command: "redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD:-redis}"
    volumes:
      - ./data/redis:/var/lib/redis
    networks:
      - jitsu
  zookeeper:
    tty: true
    platform: linux/amd64
    image: wurstmeister/zookeeper:latest
    expose:
      - 2181
    networks:
      - jitsu
  kafka:
    tty: true
    image: wurstmeister/kafka:latest
    depends_on:
      - zookeeper
    #    ports:
    #      - "19092:19092"
    #      - "19093:19093"
    environment:
      TERM: "xterm-256color"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19093,OUTSIDE://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19093,OUTSIDE://localhost:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:19092 --describe"]
      interval: 5s
      timeout: 3s
      retries: 30
    networks:
      - jitsu
  bulker:
    tty: true
    platform: linux/amd64
    image: jitsucom/bulker:latest
    restart: "unless-stopped"
    ports:
      - "${BULKER_PORT:-3045}:3042"
    environment:
      BULKER_HTTP_PORT: "3042"
      TERM: "xterm-256color"
      BULKER_KAFKA_BOOTSTRAP_SERVERS: "kafka:19093"
      BULKER_AUTH_TOKENS: "${BULKER_PASSWORD}"
      BULKER_CONFIG_SOURCE: "redis"
      REDIS_URL: "redis://default:${REDIS_PASSWORD:-redis}@redis:6379"
      BULKER_INTERNAL_TASK_LOG: '{"id":"task_log","metricsKeyPrefix":"syncs","usesBulker":true,"type":"postgres","options":{"mode":"batch"},"credentials":{"host":"${POSTGRES_HOST}","port":5432,"sslMode":"disable","database":"jitsu","password":"${POSTGRES_PASSWORD}","username":"jitsu","defaultSchema":"public"}}'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3042/ready"]
      interval: 2s
      timeout: 10s
      retries: 15
    depends_on:
      redis:
        condition: service_started
      kafka:
        condition: service_healthy
    networks:
      - jitsu
  rotor:
    tty: true
    image: jitsucom/rotor:latest
    restart: "unless-stopped"
    environment:
      DISABLE_SERVICE_prisma: "true"
      DISABLE_SERVICE_pg: "true"
      BULKER_URL: "http://bulker:3042"
      BULKER_AUTH_KEY: "${BULKER_PASSWORD}"
      KAFKA_BOOTSTRAP_SERVERS: "kafka:19093"
      REDIS_URL: "redis://default:${REDIS_PASSWORD:-redis}@redis:6379"
    depends_on:
      bulker:
        condition: service_healthy
      kafka:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - jitsu
  console:
    tty: true
    image: jitsucom/console:latest
    restart: "unless-stopped"
    environment:
      ROTOR_URL: "http://rotor:3401"
      BULKER_URL: "http://bulker:3042"
      BULKER_AUTH_KEY: "${BULKER_PASSWORD}"
      DATABASE_URL: "postgresql://jitsu:${POSTGRES_PASSWORD:-postgres}@${POSTGRES_HOST}:5432/jitsu?sslmode=disable"
      REDIS_URL: "redis://default:${REDIS_PASSWORD:-redis}@redis:6379"
      TEST_CREDENTIALS: ${TEST_CREDENTIALS}
      TEST_CREDENTIALS_SHOW_LOGIN: "true"
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET}
      SYNCS_ENABLED: ${SYNCS_ENABLED}
      SYNCCTL_URL: "http://syncctl:3043"
      SYNCCTL_AUTH_KEY: "${SYNCCTL_PASSWORD}"
      GOOGLE_SCHEDULER_KEY: ${GOOGLE_SCHEDULER_KEY}
      GOOGLE_SCHEDULER_LOCATION: ${GOOGLE_SCHEDULER_LOCATION:-us-central1
      NEXTAUTH_URL: "http://example.com/"
      UPDATE_DB: "true"
    depends_on:
      redis:
        condition: service_started
      bulker:
        condition: service_healthy
    ports:
      - "${JITSU_PORT:-8081}:3000"
    networks:
      - jitsu

networks:
  jitsu:
    name: jitsu

Need Suggestions/Fixes on this.

**Comment by vklimontovich** [comment]
How to you send the data to Jitsu. Where `example.com` from the error message is coming from?

**Comment by teenwolf99** [comment]
@vklimontovich This is how we are send the data to jitsu.
<img width="227" alt="image" src="https://github.com/jitsucom/jitsu/assets/75488209/d6f95d6a-1bce-46f6-b059-b56de9166f68">

**Comment by vklimontovich** [comment]
I believe you should change `example.com` to an actual domain where you have Jitsu deployed

**Comment by teenwolf99** [comment]
@vklimontovich I forgot to mention that example.com is not the actual domain we have used in the configuration. We are using a actual domain in the original configuration, but due to privacy of the domain we have masked it to example.com here in GitHub issue post. So we don't have problems with domain name here.
