### ISSUE TITLE
QUESTION: is possible to retrieve an user API token via API?

### ISSUE THREAD

**Issue by michelson** [jitsucom/jitsu#1068]
I have set up the auth0 provider, but I have other systems that generate this auth0, what I'm trying to do is to send the current  Auth0 API token and retrieve the internal user token via jitsu API. Is that possible? if that's not currently possible where should I have to look to create a new endpoint that validates the token and creates the user token? is there a function that auto-generates the user + token?

**Comment by vklimontovich** [comment]
Is it related to Jitsu Classic or Jitsu Next? For Jitsu Next it's not possible, we don't store plain text tokens

**Comment by michelson** [comment]
we are using the redis auth token. I think we are using the classic jitsu. golang backend /react front.
I thinking maybe I could connect directly to the redis instance to search for a auth token for a given user. I've been not investigated that part yet. but I wondering if that would be a way to go.

**Comment by vklimontovich** [comment]
Even if there's a way to fix that, it's unlikely we will ever implement it. Jitsu Classic is in maintanance mode, so we don't really want to make any changes, except bugfixes

**Comment by michelson** [comment]
Yes, we are aware of that fact, but we are kinda of stuck in that version. We are looking to implement this ourselves, so we were looking for some pointers from the experts to shed some light on how to proceed.

**Comment by michelson** [comment]
btw, I was NOT asking for you to implement anything. just asking for some hints, but well...
