### ISSUE TITLE
I have successfully deployed it,How to modify the time zone,This is not my time zone

### ISSUE THREAD

**Issue by andyWang1688** [jitsucom/jitsu#1069]
I have successfully deployed it,I tried to send the event, but found that the time of the event was incorrect. I suspect it may be a time zone issue,How to set the time zone?
![image](https://github.com/jitsucom/jitsu/assets/45682184/b78ef0f0-e5a5-4a9e-b5ae-bf973d7b08d3)

**Comment by vklimontovich** [comment]
It's a correct time - just a different timezone. We always display time in UTC in UI, and it cannot be changed, unfortunately.

**Comment by andyWang1688** [comment]
> It's a correct time - just a different timezone. We always display time in UTC in UI, and it cannot be changed, unfortunately.

Thank you ! Will the time zone be allowed to be modified during subsequent version upgrades?
