### ISSUE TITLE
Quick Start following https://docs.jitsu.com/self-hosting/quick-start

### ISSUE THREAD

**Issue by NNYGitHub** [jitsucom/jitsu#1078]
i followed the instructions on https://docs.jitsu.com/self-hosting/quick-start
in the .env file i set:

 JITSU_PUBLIC_URL=https://test.com
 JITSU_URL=https://test.com

and: GITHUB_CLIENT_ID, GITHUB_CLIENT_SECRET using https://test.com as "Homepage URL" and "Authorization callback URL"

i set up an nginx reverse proxy to access http://localhost:3000/ via https://test.com but i always get the following error:

ERROR [api]: Request for GET /api/app-config failed - {"zodError":{"issues":[{"received":"https, https","code":"invalid_enum_value","options":["http","https"],"path":["publicEndpoints","protocol"],"message":"Invalid enum value. Expected 'http' | 'https', received 'https, https'"}],"name":"ZodError"}}
Error: Response for GET /api/app-config doesn't match required schema

Did i miss any configuration option?

**Comment by absorbb** [comment]
Looks like some typo in config.
can you please try to setup on [v2.4.1](https://github.com/jitsucom/jitsu/releases/tag/jitsu2-v2.4.1)

we have simplified setup process a little:
https://docs.jitsu.com/self-hosting/quick-start
