### ISSUE TITLE
Error during deployment with helm chart

### ISSUE THREAD

**Issue by schekin** [jitsucom/jitsu#1082]
Rotor does not start with the error:

ERROR [rotor]: Connection store is not configured. Rotor will not work

version 2.4.0

**Comment by analogrithems** [comment]
our all died with the same

**Comment by vklimontovich** [comment]
We made a number of changes in `2.4.*` branch. Would you mind to go through [reference setup](https://github.com/jitsucom/jitsu/blob/newjitsu/docker/docker-compose.yml) and [documentation](https://docs.jitsu.com/self-hosting/configuration) and make sure that all variables are present in your setup.

Most likely you're missing `INGEST_REPOSITORY_URL`, `INGEST_REPOSITORY_AUTH_TOKEN` and `REPOSITORY_AUTH_TOKEN` and `REPOSITORY_BASE_URL`

If the issue persists, please feel free to reopen issue and attach a full log
