### ISSUE TITLE
Facebook Marketing Connector Source Broken

### ISSUE THREAD

**Issue by nkeat12** [jitsucom/jitsu#1087]
Please update this to the latest version
![Jitsu 02-13 at 07 40](https://github.com/jitsucom/jitsu/assets/8729807/18e2931f-c94c-4039-b14c-ca971bc3747c)

![Jitsu 02-13 at 07 39](https://github.com/jitsucom/jitsu/assets/8729807/f71ccbeb-28fe-4b25-8a5b-8c2a9ea489e1)

**Comment by vklimontovich** [comment]
Seems this relates to Jitsu Cloud. Jitsu Cloud has a special configuration, and this issue most likely is not reproducible in self-hosted Jitsu. Please contact support@jitsu.com
