### ISSUE TITLE
Feature request: Nested custom properties

### ISSUE THREAD

**Issue by gordonkjlee** [jitsucom/jitsu#1094]
## Summary
When multiple events are written to a single `events` table in the database, there are many sparse columns if events have different custom properties. One way to work more flexibly would be to write to a single JSON object/field that contains multiple properties.

## System configuration and versions
NA

## Artifacts (logs, etc)
NA

**Comment by vklimontovich** [comment]
We actully have a feature called type hints. Within the function, it's possible to tell how to treat a certain fields in the incoming ojects. Among other things, it's possible to tell Jitsu not to flatten certain fields and store it as JSON object.

We don't have documentation for it yet, but we will add it soon
