### ISSUE TITLE
Bug: setAnonymousId not working

### ISSUE THREAD

**Issue by jbmolle** [jitsucom/jitsu#1098]
## Summary

The function setAnonymousId does not set an anonymousId for a user on production server.

## System configuration and versions
Jitsu Next on K8s

I've looked at the issue #1060 and the commit fae7fde89e145c3d869ca44afd7ea8bed38a3cc0 but this is working only if `opts.debug` is true.
Only the log should be in the if and not the whole code. if opts.debug is false then the function does nothing

**Comment by vklimontovich** [comment]
The new `1.9.0` version of [NPM packages](https://www.npmjs.com/package/@jitsu/js) contains the fix
