### ISSUE TITLE
writeKey not working after migration

### ISSUE THREAD

**Issue by nizam-betterapp** [jitsucom/jitsu#1102]
## Summary

I was using jitsu self hosted that was started using docker-compose file and a writeKey was generated and deployed in my android app. I migrated my server to a new bigger machine which doesn't accept the writeKey. jitsu console is not showing any of the sites/destinations i have created. how to persist this data and use it correctly? I still have access to the older machine. can i copy some folder and fix this?

I am getting the below error.
ERRO[2024-05-04 06:41:44] [router] [batch][domain: analytics.regainapp.ai] stream not found: for: {Slug: Domain:analytics.regainapp.ai WriteKey:blahblah:blahblah IngestType:writeKey}

debian amd64

<!-- 
Is it Jitsu Classic or Jitsu Next? What is the version of Docker images you're using? 
Jitsu latest docker version

## Artifacts (logs, etc)
ERRO[2024-05-04 06:41:44] [router] [batch][domain: analytics.regainapp.ai] stream not found: for: {Slug: Domain:analytics.regainapp.ai WriteKey:blahblah:blahblah IngestType:writeKey}

**Comment by absorbb** [comment]
Hi! @nizam-betterapp all project's data is stored in postgres. So you need to migrate postgres data to the new machine

**Comment by nizam-betterapp** [comment]
Thanks. It worked!
