### ISSUE TITLE
Hubspot destination does not use additional  contact/company properties 

### ISSUE THREAD

**Issue by militarpancho** [jitsucom/jitsu#1105]
## Summary
Coming from  [here](https://jitsuhq.slack.com/archives/C018G6W0URG/p1716207913309059)

[The upsert method](https://github.com/jitsucom/jitsu/blob/77733e9311425dbb59a3cbfdd95095b0ab33a72d/libs/core-functions/src/functions/hubspot-destination.ts#L112) accepts customProps parameter but nothing is done with it.
 
## System configuration and versions
Cloud

Feel free to close it if the issue is not present, 

Cheers

**Comment by absorbb** [comment]
Fixed in [2.7.0](https://github.com/jitsucom/jitsu/releases/tag/jitsu2-v2.7.0):
By default only props that matche existing HubSpot properties will be sent
Added an option to automatically create custom properties based on received traits
