### ISSUE TITLE
Functions Config not saved from console

### ISSUE THREAD

**Issue by mabumusa1** [jitsucom/jitsu#1114]
## Summary

I can not save config from the UI, here are the steps to re-produce

1- Create a function
2- Add Config
3- Save the function 
4- Config is not saved

## System configuration and versions

Jitsu Next

**Comment by absorbb** [comment]
@mabumusa1 
Functions Config was a design concept that was unintentionally released into production.
It is now time to remove it.

For now you can configure using constants within the function code.
