### ISSUE TITLE
Authorized JavaScript Domains Ignored in Stream Settings

### ISSUE THREAD

**Issue by alexeybokov** [jitsucom/jitsu#1117]
The Authorized JavaScript Domains setting in the stream configuration is not working as expected. Events from unauthorized domains are still being tracked, even though they are not listed in the Authorized JavaScript Domains field.

Steps to Reproduce:

	1.	Create a stream.
	2.	Create a destination.
	3.	Create a connection between the stream and the destination.
	4.	Add 'mysite.com' to the Authorized JavaScript Domains field.
	5.	Add the stream snippet to the <head> section of test.com.
	6.	Observe that events from test.com are still being tracked, despite it not being listed in the Authorized JavaScript Domains.

Expected Behavior:
Events should only be tracked from domains listed in the Authorized JavaScript Domains field. Events from test.com should not be tracked in this scenario.

Actual Behavior:
Events from test.com are being tracked, indicating that the Authorized JavaScript Domains setup is being ignored.

**Comment by vklimontovich** [comment]
We are discontinued this feature, we just forgot to remove it from the UI.

If you want to filter incoming requests based on `Origin` header, you should do that with [Jitsu Functions](https://docs.jitsu.com/functions/runtime). See `headers` field of [FunctionContext](https://github.com/jitsucom/jitsu/blob/2adfa82cb6f17cb9581c46f8312a400bb8b90c1a/types/protocols/functions.d.ts#L127)
