### ISSUE TITLE
Error while loading events, show in logs of one of clickhouse shard

### ISSUE THREAD

**Issue by stouch** [jitsucom/jitsu#1119]
## Summary

Got error when loading events, but ingest, rotor and console work : 

<img width="692" alt="Capture d’écran 2024-08-20 à 12 16 49" src="https://github.com/user-attachments/assets/ef524567-4023-4ac4-9f17-416a113788d7">

shard1 error:
<img width="1062" alt="Capture d’écran 2024-08-20 à 12 18 49" src="https://github.com/user-attachments/assets/636d704e-33f1-468e-b3c9-44fe2966fa82">

And rest of services look OK : 

shard0
<img width="1064" alt="Capture d’écran 2024-08-20 à 12 19 15" src="https://github.com/user-attachments/assets/43b710ed-4084-42ef-8fe1-d022a9fa4a5e">

bulker:
<img width="800" alt="Capture d’écran 2024-08-20 à 12 20 03" src="https://github.com/user-attachments/assets/75434bc7-9b10-42b8-bf3d-c68e245ee328">

ingest:
```
│ time="2024-08-19 16:02:36" level=info msg="[metrics_server] Starting metrics server on 0.0.0.0:9091"                                                                   │││ │ ││││││  │    │         │           │                 │                                                 
│ time="2024-08-19 16:02:36" level=info msg="Starting http server on 0.0.0.0:3049"                                                                                       │││ │ ││││││  │    │         │           │                 │───────────────────────┐───────────────┐────────┐
│ time="2024-08-19 16:04:01" level=error msg="[ch_events_log] Error preparing batch: code: 60, message: Table default.events_log does not exist"  
```

## System configuration and versions

k8s install of Jitsu v2.8.0

(https://github.com/stafftastic/jitsu-chart)

**Comment by vklimontovich** [comment]
Seems like the table that for storing event logs is configured incorrectly. It should be created in `newjitsu_metrics` DB, see [compose file](https://github.com/jitsucom/jitsu/blob/newjitsu/docker/docker-compose.yml) for a reference

**Comment by stouch** [comment]
It might be because of https://github.com/stafftastic/jitsu-chart/blob/fb5d459c9c831d25c99a49981c92de43b174c1d8/templates/_helpers.tpl#L145 
-> when we use the jitsu-chart, it uses by default the "default" db. 

It changed recently ?

**Comment by stouch** [comment]
@hendrikheil  After investigation, I found that this error of unknown table does not always occur (sometimes the data load well in my console). Then I went to my k8s clickhouse shards and find out that  in one of the shard the db does not exist : 

I got 1 replica and 2 shards : 

This is the shard for which the table does not exist :

<img width="1078" alt="Capture d’écran 2024-08-21 à 15 56 43" src="https://github.com/user-attachments/assets/052fedc6-8b6e-4394-a940-6dd3c9d71d5f">

That shard does have it : 

<img width="1047" alt="Capture d’écran 2024-08-21 à 15 56 08" src="https://github.com/user-attachments/assets/0d85d1aa-ec8e-40d7-86be-bb6308aeda18">

Any idea what I could do to fix this ?
