### ISSUE TITLE
How to limit size of Clickhouse events_log table ?

### ISSUE THREAD

**Issue by stouch** [jitsucom/jitsu#1125]
## Summary

I noticed that my kubernetes clickhouse db has a table (events_log) that contains more that 1M logs in only 10 days.

Why does this table keeps storing all these past logs ? How I am supposed to limit these logs ?

I use jitsu-chart https://github.com/stafftastic/jitsu-chart  and I dont find anything about this clickhouse table limitation in https://docs.jitsu.com/self-hosting/configuration neither in jitsu-chart setup.

**Comment by stouch** [comment]
I investigated. The answer is that jitsu-chart uses a CRON to trim logs : 
https://github.com/stafftastic/jitsu-chart/blob/fb5d459c9c831d25c99a49981c92de43b174c1d8/templates/event-log-trim/cronjob.yaml#L75

This CRON uses `/api/admin/events-log-trim` jitsu/console endpoint.

In the code, this endpoint uses some env vars (https://github.com/jitsucom/jitsu/blob/newjitsu/webapps/console/pages/api/admin/events-log-trim.ts#L17), and if it does not exist, use "newjitsu_metrics" schema name, which is not the default schema that I got using jitsu-chart (I was using default values, that instanciate a "default" schema).

Anyway, to resolve this issue (but also this one https://github.com/jitsucom/jitsu/issues/1119), I added this setting in the values.yaml of jitstu-chart (https://github.com/stafftastic/jitsu-chart), which also can help this issue https://github.com/stafftastic/jitsu-chart/issues/46  : 
```
config:
  clickhouseDatabase: "newjitsu_metrics"
```

I will close this issue after the next CRON running, just to be sure.

**Comment by absorbb** [comment]
Also since [v2.8.2](https://github.com/jitsucom/jitsu/releases/tag/jitsu2-v2.8.2) that cron job already set up inside the `console` image
