### ISSUE TITLE
Console error: Authorization header with Bearer token is required

### ISSUE THREAD

**Issue by ardabeyazoglu** [jitsucom/jitsu#1128]
## Summary

Getting started with self hosted version of jitsu next and i can't access the console. All containers are running in healthy status, and all required env parameters are filled as recommended.

## System configuration and versions

console image version:
"JITSU_VERSION_COMMIT_SHA=7dd1f743e6633abe8c8eba3e7e59f9db26a94f91",
"JITSU_VERSION_DOCKER_TAG=latest",
"JITSU_VERSION_STRING=2.8.1"

## Artifacts (logs, etc)

Console url gives this error: {"error":"Authorization header with Bearer token is required"}

Docker logs:
```
jitsu-v2-console-1  | FORCE_UPDATE_DB is set, updating database schema...
jitsu-v2-console-1  | Prisma schema loaded from schema.prisma
jitsu-v2-console-1  | Datasource "db": PostgreSQL database "postgres", schema "newjitsu" at "postgres:5432"
jitsu-v2-console-1  | 
jitsu-v2-console-1  | The database is already in sync with the Prisma schema.
jitsu-v2-console-1  | 
jitsu-v2-console-1  | Starting the app
jitsu-v2-console-1  | Waiting for localhost:3000 to be up...
jitsu-v2-console-1  | Running healthcheck...
jitsu-v2-console-1  | ⚡️⚡️⚡️ HEALTHCHECK PASSED - 200 from http://localhost:3000/api/healthcheck. Details:
jitsu-v2-console-1  | {"status":"ok","prisma":{"status":"ok","ms":169},"postgres":{"status":"ok","ms":30}}
jitsu-v2-console-1  | Initializing console...
jitsu-v2-console-1  | {"success":true}
```

**Comment by johnpitchko** [comment]
What URL are you accessing? What is in your env vars? I've encountered this issue a few times when trying to access a URL that I shouldn't be.

**Comment by ardabeyazoglu** [comment]
Forgot to close this. I managed to solve it. issue was misconfiguration of reverse proxy
