### ISSUE TITLE
Adding Elestio as deployment option

### ISSUE THREAD

**Issue by kaiwalyakoparkar** [jitsucom/jitsu#1129]
Hey team,
I am Kaiwalya, Developer Advocate at Elestio. Elestio has been providing options of fully deploying and managing Jitsu application as shown [here](https://elest.io/open-source/jitsu). I think it would be a great idea if we can add it to official readme/documentation here.
🔔 In addition to this, if you are interested we provide partnership opportunities with tools we support by **revenue share** upon addition of this method in docs. If you would like to collaborate, just shoot me an email at [kaiwalya@elest.io](mailto:kaiwalya@elest.io) :)

**Comment by vklimontovich** [comment]
Seems like you have an old version (Jitsu Classic) on you platform. Any chance you support Jitsu 2.0? Jitsu Classic is reaching end of life and we don't really want to promote it

**Comment by kaiwalyakoparkar** [comment]
Hey @vklimontovich, 
Our service is a new one https://github.com/elestio-examples/jitsu/blob/main/docker-compose.yml based on your repo https://github.com/jitsucom/jitsu/blob/newjitsu/docker/docker-compose.yml . Is that what you mean when you say Jitsu classic?

**Comment by vklimontovich** [comment]
https://elest.io/open-source/jitsu - screenshots in here are from Jitsu 1.0 (aka Jitsu Classic), the old generation of Jitsu

**Comment by kaiwalyakoparkar** [comment]
Hey seems like it's Jitsu 1.0 then. I have forwarded this message to our development team and will get back to you about Jitsu 2.0 :)

**Comment by kaiwalyakoparkar** [comment]
Hey @vklimontovich, should I go ahead and create a pull request for this?
