### ISSUE TITLE
Inviting users to self-hosted deployment does not work

### ISSUE THREAD

**Issue by johnpitchko** [jitsucom/jitsu#1131]
## Summary

In the Console, I sent a few invitations to colleagues to sign into to Jitsu.

First, they never received an email invitation from Jitsu. This makes sense because I do not recall Jitsu requesting any email credentials in the env file or elsewhere.

Second, I sent them the invitation link generated in Console. When clicking, the user is navigated to the Console sign in page with the standard form asking for email and password with a *Sign in* button, rather than fields for specifying and confirming a new account password.

## Artifacts (logs, etc)

Generated invitation code:
<img width="599" alt="Screenshot 2024-09-25 at 15 34 16" src="https://github.com/user-attachments/assets/113c7013-0f98-4f5b-8db7-48e1930eb07a">

Sign in page present
<img width="437" alt="Screenshot 2024-09-25 at 15 34 37" src="https://github.com/user-attachments/assets/d341395a-a68a-447a-9c70-d7a01bac3871">
ed after opening link in private window:

**Comment by johnpitchko** [comment]
I was able to get the mail to send by adding the `SMTP_CONNECTION_STRING` env var. I dont' recall seeing this in the docs page but could be mistaken.

**Comment by johnpitchko** [comment]
Dug around the app a ton more and I think I understand what is going on. There is no signup page, or at least there is but its disabled by default. So the only say to support multiusers in the same workspace is to:

1. Enable OAuth via Github.
2. Have the other user register/signup to Jitsu through Github OAuth.
3. Send the invitation link to the other user via Jitsu console.
4. Have the other user accept the invite.

**Comment by stouch** [comment]
I got this issue too.  :'(

(and thx for the last answer but we dont want/need to use github auth)

**Comment by johnpitchko** [comment]
@stouch there is obviously places in the codebase to allow user signup, but its linked to some Firebase app config setting which I have not deciphered yet. Still hacking away...

**Comment by vklimontovich** [comment]
Thats correct, Jitsu have 2 authorization mechanism. One is based on Firebase and used on [Jitsu Cloud](https://use.jitsu.com). The second one is based on [Next-Auth](https://next-auth.js.org/) and supports GitHub and Password Auth. 

You can probably use Firebase too, but only Next-Auth has been tested for self-hosted installations. We do not plan test and support invitation workflow for self-hosted installations. We don't see a good use-case for it. Usually Jitsu managed by dev ops team and they either ok sharing password across the team, or us individual GitHub accounts (I suppose every devops have a GitHub account). GitHub account invitations should work in self-hosted Jitsu

**Comment by stouch** [comment]
I think there is a misunderstanding of this issue : The jitsu flow is actually really broken and we cannot invite any user even when we give them the invitation link (see the author screenshots). 

We should definitely re-open this issue
