### ISSUE TITLE
Identity stitching not updating traits in single table layout

### ISSUE THREAD

**Issue by ardabeyazoglu** [jitsucom/jitsu#1133]
## Summary

`jitsu.identify(123456, {email: "test@example.com", mobile: "5556668877");` adds identify events to clickhouse destination, and properly add `user_id` and `context_traits_email`, however; only `user_id` is updated on previous anonymous records. Isn't it more correct to update traits as well ? This is especially important when user_id is not used (or set to null), because we need to query by traits rather than user_id.

## System configuration and versions

Latest jitsu 2.8.2

**Comment by absorbb** [comment]
Hi @ardabeyazoglu 

We couldn't reproduce this issue on our setups.

Could you please check the following:

- That Identity Stitching is still enabled in connection settings – jitsu 2.8.2 has a bug that could lead to disabling of Identity Stitching on changing Functions setup.
- Please check the "API Destinations & Functions Logs" tab in the Data -> Live Events section for the CH connection. It must contain a line like that one: `*** events for anonymous id: *** was updated with id fields: {"userId":"***","context":{"traits":{***}}} by Message ID:***` Please check whether all expected traits are mentioned in these messages.
- Please confirm that you select from the destination table using `FINAL` keyword. With Clickhouse we rely on [eventual de-duplication](https://github.com/jitsucom/bulker/blob/main/.docs/db-feature-matrix.md#clickhouse-deduplication) of MergeTree engines family.

**Comment by ardabeyazoglu** [comment]
Thanks, I will check as soon as i have time.

**Comment by absorbb** [comment]
Fixed in [2.10.0](https://github.com/jitsucom/jitsu/releases/tag/jitsu2-v2.10.0)
