### ISSUE TITLE
Cannot build Docker images - build process freezes

### ISSUE THREAD

**Issue by johnpitchko** [jitsucom/jitsu#1145]
## Summary

The Docker image build appears to freeze/stall during building. 

The command I am running to build the images: `docker buildx build --platform linux/amd64 . -f all.Dockerfile`

The build process starts, but freezes during the `RUN pnpm build` step. As you can see in the screenshot, the build has been running for >1300 seconds (20 minutes).

<img width="1284" alt="Screenshot 2024-11-14 at 13 54 44" src="https://github.com/user-attachments/assets/b5a42d65-c633-440d-98cf-dbf25946ee1c">

## System configuration and versions

Using Jitsu Next on latest `main` branch. Docker version 27.2.0.

**Comment by johnpitchko** [comment]
Curiously, dropping the `--platform linux/amd64` argument allowed the build to succeed:
<img width="1280" alt="Screenshot 2024-11-14 at 14 08 50" src="https://github.com/user-attachments/assets/0e50b080-311b-4e90-982e-10d1f67ed779">

**Comment by vklimontovich** [comment]
Are you building this on Apple Silicon? They have a pretty poor simulation layer for arm64

**Comment by johnpitchko** [comment]
👋 yes I am on a Macbook Pro M1. If that is the case, I can look into other solutions to build the image. Are you on Apple Silicon and if so, what do you use to build?

**Comment by vklimontovich** [comment]
For local development, just drop `--platform` option, and it will build a native arm64 image. If you want to deploy it somewhere, I believe it's going to be amd64, so the best way to do so is to get a AMD64/Linux instance from any cloud provider. That's what we use in our CI/CD workflow

Another approach would be using [docker build cloud](https://www.docker.com/products/build-cloud/). We have a plans to switch to it and add a support to build scripts, but we are not there yet. But you can try hack the script and maybe make a PR

**Comment by johnpitchko** [comment]
That's cool thank you. Also, pardon my Docker newbie question, but I noticed that only a single image is put from from that script. I assume that image is for the Console. How do I build images for Ingest and Rotor and Bulker (but I believe that is in a separate repo)?

PS is your documentation in a public repo? I would be happy to contribute to it as I tinker with the self-hosted version.

**Comment by vklimontovich** [comment]
It's a [multi-stage docker file](https://docs.docker.com/build/building/multi-stage/), meaning it can produce several images. It's controlled by `--target` option. I don't believe we use `./consolebuild.sh` anywhere. Look at `pnpm run build-scripts`, and `./release.sh`.

**Comment by vklimontovich** [comment]
Closing this one since nothing should be done here

**Comment by johnpitchko** [comment]
Agreed - thank you for your help @vklimontovich
