### ISSUE TITLE
Searchable select elements

### ISSUE THREAD

**Issue by epuluikis** [jitsucom/jitsu#1147]
## Summary

The current implementation of select elements doesn't support search functionality. For teams with a large number of sources, it becomes time-consuming to find the desired option. Adding a search to select elements would dramatically improve UX.

As far as I'm aware, it should only require adding a `showSearch` attribute to the select element.

I could make a PR if the scope is provided for which selects to enable search (if not for all).

## System configuration and versions

Jitsu Next - console

**Comment by vklimontovich** [comment]
We'd gladly accept PR like this! Though I'm not sure I about which select you're taking - we have multiple. Would you mind attaching a screenshot?

**Comment by epuluikis** [comment]
I primarily use the Site select on the Live Events page. However, this issue also affects other selects, such as the Source select on the Create Connection page. Because of this, I’d need guidance on which selects should be made searchable.

**Comment by vklimontovich** [comment]
Got it. I think it makes sense to make most selects searchable. It should be easy for most of them, since they are all based on antd's Select and it looks like you just need one prop to enable search. Let's start with just one to see how easy it is, and take it from there
