### ISSUE TITLE
Microservices and Jitsu

### ISSUE THREAD

**Issue by cloudcompute** [jitsucom/jitsu#1151]
Hi

Does it make sense using Jitsu along with microservices.. does it fit somewhere in the Event-driven microserices architeure?

For instance, a micoservice A writing to its Database and changes in the DB are getting CDCed to Jitsu (Kafka) and other microservices B and C reading and processing those events (CQRS architecure.. reads and writes are separate) and displaying the results in almost real-time? Is this kind of flow possible if we use Jitsu for implementing event driven and separating reads and writes? Secondly, will it be performant / scalable?

I can understand its basic goal is to achieve analytics. But can Jitsu be used for the applications built using microservices where results should be instantaneous?

Thanks

**Comment by vklimontovich** [comment]
Please address this question to community slack: https://jitsu.com/slack. The github should be used only for reporting issues, or suggesting features
