### ISSUE TITLE
Limit number of columns

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#140]
### Problem

Currently, a mistake in the code can generate an endless number of columns in the database.

### Solution

Let's have a setting `max_columns` (per destination) that is 100 by default. If during schema patching number of columns has exceeded, let's fail the whole process - row or whole batch.

**Comment by Alessar** [comment]
@vklimontovich It looks like a simple error checking.
Should `max_columns` be different for different destinations?
Or we can just simply use one setting for all destinations at all?
