### ISSUE TITLE
Dropin tracker for Intercom

### ISSUE THREAD

**Issue by guillaumemeyer** [jitsucom/jitsu#143]
### Problem

For apps that don't use Google Analytics nor Segment, but are using Intercom tracker, it requires to manage both Intercom code and EN code.

### Solution

Having Intercom.js tracker natively managed just as GA or Segment would ease the integration with EN.

**Comment by vklimontovich** [comment]
Hi @guillaumemeyer! Thank you for submitting the issue!

Overall, it could be a great addition to EventNative, however, adding more interceptors is not a priority now. I'm going to keep it open, but it's unlikely the core team will implement this any time soon.

That being said, we have a plugin system for adding interceptors. We're welcome a contribution from the community!
