### ISSUE TITLE
Parse json strings with datetime as SQL timestamp

### ISSUE THREAD

**Issue by xtreding** [jitsucom/jitsu#171]
### Problem

At present *EventNative* parse all JSON strings as strings and creates SQL columns with text type by default (if typecast isn't configured). Sometimes it is inconvenient to configure explicit SQL timestamp typecasts to every field. It can be recognized by default.

### Solution

All input JSON strings with ISO DateTime format patterns (`2006-01-02T15:04:05.000000Z` or `2006-01-02T15:04:05.000Z`) must be parsed as timestamp and be mapped into SQL type as SQL timestamp.

**Comment by guillaumemeyer** [comment]
Need that
