### ISSUE TITLE
User interface for sources configuration

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#213]
We need a user interface to configure [sources](https://docs.eventnative.org/configuration-1/sources-configuration).

For that following steps are required:

- [x] Define list of parameters in [Connectors Catalogs](https://github.com/jitsucom/connectors-catalog)
- [x] Implement UI to configure sources and save JSON them into Redis (via API)
- [x] Implement API call to export all configured connectors
- [x] Implement Periodic loading source configuration in EventNative (like destination configuration)
- [x] Implement test source API call (see #141 )

**Comment by xtreding** [comment]
Test sources endpoint:
POST `https://app-api.jitsu.com/api/v1/sources/test`

```
{
    "status": "Connection established"
}
```
