### ISSUE TITLE
Add auto-discover for Singer connectors

### ISSUE THREAD

**Issue by xtreding** [jitsucom/jitsu#372]
### Problem

1. Singer catalog.json is complicated to use because:
- JSON is huge 
- User has to mark every stream with `"selected": true`.

We should improve our user's experience with Singer.

2. At present it is impossible to resync all data (if it has been already synced). We should have an endpoint to clear the connector's state.

2. 
### Solution

1. Jitsu Server should run Singer `discover` if catalog.json isn't provided and should mark all streams with `"selected": true`.
Also, there should be a list of Singer taps names that use properies.json instead of catalog.json.

2. Create POST `/api/v1/sources/clear_cache` endpoint that clears source cache (`source#${source_id}:collection#${tap_name}:chunks` per collection.

**Comment by vklimontovich** [comment]
Clear cache should be available for non-singer connectors as well
