### ISSUE TITLE
Cookie-less tracker

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#381]
### Problem

If Jitsu user failed to obtain cookie consent from website visitor (or doesn't want to use cookie at all), we still should be able to track something

### Solution

The exact solution should be discussed. However, interface should be pretty clear, it should be controlled by `cookieless` parameter.

```
const jitsu = jitsuClient({
   cookieless: true
   ...rest
})
```
### Bonus track

We need to introduce a setting `ip_resolver.remove_last_octet` to be GDPR complient

**Comment by lekoala** [comment]
it would be great to have something similar to what https://github.com/fingerprintjs/fingerprintjs provides :-)
