### ISSUE TITLE
Redis API connector should support sync by key mask

### ISSUE THREAD

**Issue by xtreding** [jitsucom/jitsu#393]
### Problem

At present Redis API connector supports only hash keys. It is useful to sync all Redis data and Jitsu should support it. Also, it is suitable to sync Redis keys by mask (e.g. `key1:subkey*`)

### Solution

- [ ] Redis driver (`drivers.Redis`) configuration should contain `redis_key_mask` field, that can contain `key1:subkey*` value. 

- [ ] Redis driver should support syncing sets, sorted sets, plain keys

**Comment by xtreding** [comment]
Jitsu will get key by mask with cursor: `SCAN $cursor MATCH $redis_key_mask COUNT 5000` and iterate over the result:
- get type of the key (`type $key`)
- depend on the type get key-value and extract it:

1. [String key](https://redis.io/commands/get): get key and extract value if json:
`redis_key1` : `{"key1": "123", "key2": "abc"}`

store into a table like:

|     redis_key      | key1 |   key2   | 
| ------------- | ---------- |  ---------- | 
|   redis_key1   |    "123"    | "abc" |    

or if a plain string value:

|     redis_key      | value | 
| ------------- | ---------- | 
|   redis_key1   |    "value"    |

2. [Hash key](https://redis.io/commands/hgetall): get key and extract values if json:

`hash_key`: 
  `hash1`:`{"key1": "123", "key2": "abc"}`
  `hash2`:`{"key1": "456", "key3": "qwe"}`
  
|     redis_key   | redis_hash |   key1   |  key2 |
| ------------- | ---------- |  ---------- |  ---------- | 
|   hash_key   |    hash1    | "123" |  "abc" |
|   hash_key   |    hash2    | "456" |  "qwe" |   

or if a plain string value:

|     redis_key      | redis_hash | value | 
| ------------- | ---------- | ---------- | 
|   redis_key1   |    hash_key| "value"    |

3.  [List key](https://redis.io/commands/lrange): get size of the list and then use LRANGE with parts and extract values if json:
`redis_key1` : `[{"key1": "123", "key2": "abc"},{"key1": "456", "key3": "qwe"} ]`

store into a table like:

|     redis_key      | key1 |   key2   | 
| ------------- | ---------- |  ---------- | 
|   redis_key1   |    "123"    | "abc" |    
|   redis_key1   |    "456"    | "qwe" |    

or if a plain string values:
`redis_key1` : `["aaa", "bbb"]`

|     redis_key   | value | 
| ------------- | ---------- | 
|   redis_key1   |    "aaa"    |
|   redis_key1   |    "bbb"    |

4. [Set key](https://redis.io/commands/smembers):extract values if json:
`redis_key1` : `[{"key1": "123", "key2": "abc"},{"key1": "456", "key3": "qwe"} ]`

store into a table like:

|     redis_key      | key1 |   key2   | 
| ------------- | ---------- |  ---------- | 
|   redis_key1   |    "123"    | "abc" |    
|   redis_key1   |    "456"    | "qwe" |    

or if a plain string values:
`redis_key1` : `["aaa", "bbb"]`

|     redis_key   | value | 
| ------------- | ---------- | 
|   redis_key1   |    "aaa"    |
|   redis_key1   |    "bbb"    |

5. [Sorted Set key](https://redis.io/commands/zrange):extract values if json:
`redis_key1` : `[{"key1": "123", "key2": "abc"},{"key1": "456", "key3": "qwe"} ]`

store into a table like:

|     redis_key      | key1 |   key2   | 
| ------------- | ---------- |  ---------- | 
|   redis_key1   |    "123"    | "abc" |    
|   redis_key1   |    "456"    | "qwe" |    

or if a plain string values:
`redis_key1` : `["aaa", "bbb"]`

|     redis_key   | value | 
| ------------- | ---------- | 
|   redis_key1   |    "aaa"    |
|   redis_key1   |    "bbb"    |

**Comment by vklimontovich** [comment]
Can we support something like this: if key ends with `*` (`key*`) we do scan. Otherwise, we just get on key?

**Comment by xtreding** [comment]
Absolutely
