### ISSUE TITLE
Jitsu sdk-js 2.2.1 broke the package

### ISSUE THREAD

**Issue by ajimix** [jitsucom/jitsu#402]
## Description

The release done few hours ago of 2.2.1 broke the node package after updating.

## Steps to reproduce

Upgrade `@jitsu/sdk-js` from 2.2.0 to 2.2.1 and the files inside the package are gone

## Expected behavior

Files should be in the `node_modules` folder like it was in 2.2.0. See below the same command with 2.2.0

```
$ ls node_modules/@jitsu/sdk-js/

dist  package.json  README.md
```

## Actual behavior

After upgrading to 2.2.1 the files are gone

```
$ ls node_modules/@jitsu/sdk-js/

README.md    package.json
```

You can see yourself by downloading the node package

https://registry.npmjs.org/@jitsu/sdk-js/-/sdk-js-2.2.1.tgz

vs 

https://registry.npmjs.org/@jitsu/sdk-js/-/sdk-js-2.2.0.tgz

**Comment by vklimontovich** [comment]
Thank you for reporting this. I unpublished 2.2.1 for the time being. We'll republish it tomorrow (seems like a build script bug)

**Comment by vklimontovich** [comment]
This is fixed. `2.2.2` without this issue has been published
