### ISSUE TITLE
GIF Tracking pixel 

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#416]
### Problem

For some environments (such as email) JS SDK will not work. We need to fallbackt to old-school GIF tracking pixel

### Solution

End-point `/api/v1/p.gif` (GET). Parameters: `data=` or `path.to.json.node`. 

Processing pipeline generally consists from two steps: 1) restore payload JSON 2) inject additional data based on headers.

#### Restoring JSON

* If `data` parameter is present - treat the value as base64 encoded JSON object, otherwise start with empty `{}` object
* For each parameter (except `data`), treat it as path to json node with value. E.g. /api/v1/p.gif?context.a.b=1&context.b=x will be decoded to `{context: {a: {b: 1}, b: "x"}}`
* If `compat` field is present in JSON, enable compatibility mode

#### Injecting additional data

Unless the field is present, the following values should be added

* `/url` (`/eventn_ctx/url` in compat mode) — take from referer header
* `/doc_host` (`/eventn_ctx/doc_host` in compat mode), `/doc_path` (`/eventn_ctx/doc_path` in compat mode), `/doc_search` (`/eventn_ctx/doc_search` in compat mode) parse `url`
* `/user/anonymous_id` (`/eventn_ctx/user/anonymous_id` in compat mode) — identify user based on cookie. Cookie domain should be taken from `Host` header, unless `cookie_domain` node is present in JSON.
* `/user_agent` (`/eventn_ctx/user_agent` in compat mode) take from the header
* `/utc_time` (`/eventn_ctx/utc_time` in compat mode) - current time in UTC as ISO string
* `/src` - 'jitsu_gif'

As a response empty transparent GIF should be served

**Comment by absorbb** [comment]
Keep in mind that some mail clients (at least Gmail web client) load images in s2s manner
