### ISSUE TITLE
Cookie-less mode not having an user identification 

### ISSUE THREAD

**Issue by militarpancho** [jitsucom/jitsu#525]
When using data-privacy-policy=true to collect events without user consent, i don't see the hash (user_agent + ip address) that you mention in the docs.

An event example to illustrate the issue: 

```
api_key: "js*****"
click_id: {}
doc_encoding: "UTF-8"
doc_host: "www.**********.com"
doc_path: "/plans"
doc_search: ""
event_id: ""
event_type: "Pricing"
ids: {fbp: "fb.1**************", ga: "GA1.2****************"}
local_tz_offset: -120
page_title: "Plans"
referer: "https://*****/plans"
screen_resolution: "1920x1080"
src: "jitsu"
url: "https://www.graphext.com/plans"
user: {anonymous_id: ""}
user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36"
user_language: "en-GB"
utc_time: "2021-09-03T12:33:49.727000Z"
utm: {}
vp_size: "1916x309"
```

Maybe it's my fault and I'm doing something wrong....but i'm expecting the anonymous id field not to be empty. Thanks in advance guys for all your work, we appreciate it a lot.

Cheers, Manuel

**Comment by xtreding** [comment]
Hi @militarpancho! Thank you! 

Is your event example from the browser network console? Because Jitsu backend sets anonymous id field and you can see it already in your data warehouse.

You've written `data-privacy-policy=true` but the correct option is `data-privacy-policy=strict`, may be it is an issue.

**Comment by militarpancho** [comment]
Yep, that was the problem, The ids are added in jitsu server!!, thanks for the help! Cheers!
