### ISSUE TITLE
Error: Failed to send JSON

### ISSUE THREAD

**Issue by masminto** [jitsucom/jitsu#538]
I've issue for package @jitsu/sdk-js version 2.2.4 , it's getting Error apply(@jitsu/sdk-js/dist/npm/jitsu.cjs) on iOS device

**Comment by vklimontovich** [comment]
Hi @masminto! Thank you for submitting the issue!

Could you please provide more details. 
 - When do you see this error? Is it runtime or build time?
 - Could you please provide more info about iOS environment (if error is runtime). Is it Safari or other browser?
 - If possible, could you please attach screenshot and track trace of the error?

**Comment by masminto** [comment]
Hi, I see this error in run time. it actually happened in both chrome mobile iOS and mobile safari.
here is the log in sentry:
```
[
   [
      "J-ERROR"
   ]"Failed to send",
   {
      "event_id":"",
      "user":{
         "anonymous_id":"lw7cfvpddf"
      },
      "ids":{
         "ga":""
      },
      "user_agent":"Mozilla/5.0 (iPhone; CPU iPhone OS 14_7_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.1.2 Mobile/15E148 Safari/604.1",
      "utc_time":"2021-09-10T03:51:35.867000Z",
      "local_tz_offset":-480,
      "referer":"",
      "url":"",
      "page_title":"",
      "doc_path":"",
      "doc_host":"",
      "doc_search":"",
      "screen_resolution":"375x667",
      "vp_size":"375x553",
      "user_language":"en-gb",
      "doc_encoding":"UTF-8",
      "utm":{
         
      },
      "click_id":{
         
      },
      "api_key":"",
      "src":"jitsu",
      "event_type":"result-page",
      "occured_at":1631245895,
      "session_id":"01ad96ab-dcaa-414e-be4a-4c25b6749545",
      "auid":"6deb710f-b8fd-41cb-9690-d680272a41cf",
      "cdn_country":"MY",
      "fingerprint":"",
      "currency":"MYR",
      "language":"en",
      "user_id":"",
      "user_email":"",
      "page_url":"",
      "referral_url":"",
      "campaign_id":"",
      "traffic_source":"GADS",
      "source_type":"",
      "platform":"web",
      "dvce_type":"mobile",
      "dvce_id":"",
      "dvce_ip_longitude":"",
      "dvce_ip_latitude":"",
      "product":"",
      "screen_name":"search-result",
   }
],
```

**Comment by vklimontovich** [comment]
Hi @masminto! I suspect this is a network issue. How you configured Jitsu? What have you used as `tracking_host` while configuring Jitsu client? 

[Here's the snippet where the error happens](https://github.com/jitsucom/jitsu/blob/f9ee02bedac2e183ac70eb70882f8a215d6630cb/javascript-sdk/src/jitsu.ts#L212)(`jitsu.ts`)

```
      req.onerror = (e) => {
        getLogger().error('Failed to send', json, e);
```

[As per specification](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequestEventTarget/onerror), `onerror` is being called only when the host is unreachable (or other network error happened). To help you further, could you please:
 - Attache a full error snippet. After event JSON, it should be an error description
 - Check what you see in DevTools/Network inspector tab?. Any errors?

Meanwhile, I'll release a small patch that improves logging a little bit and makes it more clear

**Comment by masminto** [comment]
Hi @vklimontovich my apologies for the late reply. I've been busy searching for your request (full error snippet, and errors in network inspect) I can't find the error snippet other than in sentry. 

I configured jitsu using @jitsu/sdk-js version 2.2.4 and using my own server for the `tracking_host`

but why I only get log `onerror` only on iOS device? could you please release small patch that improves logging? Thank You

**Comment by masminto** [comment]
Here's the log after I updated to `@jitsu/sdk-js@2.2.5` :
`Failed to https://[hostname] /api.iyzjo?p_7dpdt=788e8546-e019-11eb-ba80-0242ac130004 load resource: The network connection was lost.`

it seems network connection lost but I think is about aborted request. The issue only reproduced in safari browser

**Comment by vklimontovich** [comment]
`https://[hostname] /`means that you're passing literally `[hostname] ` to jitsu js SDK. The SDK sends data to `[hostname] ` and fails. It seems like some templating issue happening before jitsu initialization

**Comment by masminto** [comment]
I think it's not the about the templating, it's about the aborted request and I already fix it with validate logging to sentry. Thank you.
