### ISSUE TITLE
Generate user_anonymous_id (ip+user_agent hash) in normal mode 

### ISSUE THREAD

**Issue by militarpancho** [jitsucom/jitsu#539]
We're trying to use the new GDPR compliance mode for our landing page. We'd need to match events with only `user_anonymous_id` (collected with jitsu in privacy mode) with events collected with the "normal" mode of jitsu. 
If we can have this `user_anonymous_id` being calculated in the normal mode too, for matching anonymous events with identified events I think it should be very useful. Thanks in advance!

**Comment by absorbb** [comment]
Fixed in [v1.35.2](https://github.com/jitsucom/jitsu/releases/tag/v1.35.2)
Added an extra field `hashed_anonymous_id` field for `user` object that always added for js and pixel endpoints

**Comment by militarpancho** [comment]
Thanks for this!!, It will be very useful for us!
