### ISSUE TITLE
Airbyte sources will not work in Jitsu deployed on Kubernetes 

### ISSUE THREAD

**Issue by amadrizwan** [jitsucom/jitsu#545]
## Description
When running jitsu on kubernetes, airbyte sources do not work. Jitsu server generates the following stack trace:

```
2021-09-21 14:03:22 [ERROR]: Error pulling airbyte image:
	exec: "docker": executable file not found in $PATH
```

## Steps to reproduce
Spin up a single pod of jitsucom/jitsu:beta docker image in kubernetes. Open configurator, add an airbyte source and it will throw this error.

Alternatively, set up a jitsu server in kubernetes and configure an airbyte source (any) via cfg file. 

## Expected behavior
In order for airbyte to run, jitsu/eventnative spins up airbyte docker images. This requires jitsu server to have access to docker client. There are two alternatives to run airbyte docker images from jitsu in kubernetes. Docker out of docker (DooD) and docker in docker (DinD) [1]

But for any method to be implemented, docker client/executable needs to be present in the server docker image which is missing currently. [2]

[1] https://applatix.com/case-docker-docker-kubernetes-part-2/
[2] https://github.com/docker-library/docker/blob/master/20.10/Dockerfile

## Actual behavior
airbyte containers cannot run as docker client/executable is missing

**Comment by absorbb** [comment]
Hi @amadrizwan 

We have just added docker exec to latest jitsucom/server beta image.
May you please check whether it helps with your case?
