### ISSUE TITLE
Can't load to mysql.

### ISSUE THREAD

**Issue by Data-bytes305** [jitsucom/jitsu#548]
I enjoy jitsu project.   In first use, I encountered an error.

[ERROR]: System error: Error setting hashed anonymous ID: Unnable to set value with multiple JSON paths [/eventn_ctx/user/hashed_anonymous_id||/user/hashed_anonymous_id] into object: map[age:124 id:2 name:zy source_ip:127.0.0.1 user_agent:PostmanRuntime/7.28.4]

YAML:

 server:
  name: instance1.domain.com
  port: 8089
  admin_token: 1q2w3e
  public_url: https://instances.domain.com
  disable_welcome_page: true
  log:
    path: /Users/zy/Desktop
  metrics.prometheus.enabled: true

log:
  path: /Users/zy/Desktop/events
  rotation_min: 5

api_keys:
  - id: my_website_key
    client_secret: '193b6281-f211-47a9-b384-102cf4cd2d55'
    server_secret: 'a6880b16-73d0-476e-840a-804b74f7684d'

destinations:
  mysql:
    type: mysql
    only_tokens: ['my_website_key']
    data_layout: #Optional
      table_name_template: events
      primary_key_fields: ['id']
    datasource:
      host: 127.0.0.1
      db: event
      port: 3306
      username: root
      password: admin123
      parameters:
        tls: false
        timeout: '300s'

![image](https://user-images.githubusercontent.com/83893570/134522260-06e7e5b3-1247-44b3-8e09-5c0e187d8176.png)

**Comment by absorbb** [comment]
Hi! @Data-bytes305 
Thank you for the report. It is not critical error – it doesn't stop Jitsu from doing its job.
We will remove it in the next hotfix release that will happen today or tomorrow.

**Comment by absorbb** [comment]
Fixed in Jitsu 1.35.4
