### ISSUE TITLE
Redis sentinel support

### ISSUE THREAD

**Issue by viggin543** [jitsucom/jitsu#553]
### Problem

Supporting HA redis configuration ( sentinel mode )

HA is a production requirement and redis without HA is a single point of failure. 

### Solution

Use redis sentinel client ( it's a different client than the regular redis client ) . 
The client handles redis failover a by reconnecting to the new master .

This will require to manage two redis clients , since sentinel / non sentinel redis clients are not compatible .

**Comment by vklimontovich** [comment]
Hi @viggin543! It's relatively simple to change. Jitsu uses [redigo](https://github.com/gomodule/redigo) and seems it works well with Sentinel [via plugin](https://github.com/FZambia/sentinel). We need just to change initialization, the data manipulation API is the same.

However, we'll need to do some devops work to set up cluster and test it properly. So expected ETA is mid-Oct. But PRs are always welcome :)

**Comment by viggin543** [comment]
@vklimontovich  looks like something I can do. hope you did not begin working on it yet. I Will attach a PR to this issue in a couple of days.

**Comment by absorbb** [comment]
@viggin543  We didn't started. Your PR will be appreciated.
Thank you!

**Comment by viggin543** [comment]
@absorbb pr linked
