### ISSUE TITLE
Session Support for Pixel/SDK

### ISSUE THREAD

**Issue by azhard4int** [jitsucom/jitsu#555]
### Problem

Currently, SDK sends page view events when the user loads a page/website, but one key information missing is sessions. Without sessions, we are missing to find out how long did the user use the web application before they closed the web page. What most of the applications are doing is they send a `session_started` event when the Dom is loaded and  when the user exit the page, an event `session_ended` is sent.

<img width="557" alt="Screenshot 2021-09-27 at 4 37 08 PM" src="https://user-images.githubusercontent.com/11090179/134919332-1b70f7f5-6392-49fa-add8-e7e35b26970d.png">

### Solution

Proposed solution: architecture, implementation details etc

1. Provide an option on Pixel/SDK and make this it as an optional field: `isSessionEnabled`. By default the option is set to False.
2. If the option `isSessionEnabled` is enabled, send a `session_started` event along with Page View. When the user is closing the tab, `session_ended` event can be triggered.

**Comment by vklimontovich** [comment]
@azhard4int we'll take a look. Probably that's something we can release mid-October.

However, I don't think `session` is a good description of this feature. Usually, sessions are a sequence of different page views that happens in a short time window (btw, we have [DBT sessionazation](https://hub.getdbt.com/jitsucom/dbt-jitsu/latest/) package). 

If we stick with following:

 - Add `page_left` event if `shouldTrackPageLeft` is set to true
 - Keep original `page_view`
 - Add `secondsOnPage` to `page_left` event 

Will it solve your problem?

**Comment by azhard4int** [comment]
@vklimontovich Thanks for getting back.

Yes, page_left event would be good enough to achieve the above functionality.

**Comment by azhard4int** [comment]
@vklimontovich  We are building our SaaS on top of Jitsu, if we were using for our own company/product, we could go with the option that you suggested.

So, we'll wait for this to be added in December or so.
