### ISSUE TITLE
[Server] Support Airbyte connectors versions

### ISSUE THREAD

**Issue by xtreding** [jitsucom/jitsu#606]
### Problem

At present, Jitsu Server doesn't know about Airbyte connectors version. Therefore connectors aren't updated automatically and users should manually do that. Since connectors are being actively developed and updated, we should support it. 

### Solution

Each configured Airbyte source connector should have a docker version. By default docker version = latest.
 tagged version from docker hub API . Users should be able to set a certain version of the connector in Configurator UI.

- [x] Jitsu Server `/versions` endpoint should return a sorted array of available docker versions where the first element is the certain latest version. (requests them from https://hub.docker.com/v2/repositories/${DOCKERHUB_REPO}/${DOCKERHUB_IMAGE}/tags?page_size=1000)

The response will be:
```
{
  "versions": ["1.1.1", "1.1.0", "1.0.0", "0.0.1"]
}
```

- [x] Jitsu Server should use `image_version` from connector configuration in every Airbyte docker run

**Comment by vklimontovich** [comment]
I like the approach, but let's make a few amendments to make PR backward-compatible:

 - Support of `image_version: latest`. In this case runner should pick latest available version
 - If `image_version` is absent, the default value is `latest`

Just to clarify, `versions` will contain an array of all versions available on dockerhub? Does it mean that every spec request will take at least a few seconds? (Not a blocker, we just need to account for that while planning UX)
