### ISSUE TITLE
Enrich events with cloud/company information

### ISSUE THREAD

**Issue by mike0sv** [jitsucom/jitsu#625]
### Problem

We use jistu for sending telemetry events for our cli/framework. It would be nice to know, which cloud providers our users use the most, along with information about a company, which can be known from IP address, like geo fields.

### Solution

There is a library which does it https://github.com/bcoe/which-cloud. And maybe maxmind also have those databases, but I didn't check.

**Comment by vklimontovich** [comment]
Now Jitsu can pull company data from MaxMind DB. Here's the: https://jitsu.com/docs/other-features/geo-data-resolution
