### ISSUE TITLE
Jitsu Mapping Different field cause hard to trace the root cause of the problem. 

### ISSUE THREAD

**Issue by hamrio** [jitsucom/jitsu#633]
## Description
I found that jitsu has miss mapping while trying to insert into the database. 

this is the error message
`clickhouse: Code: 62, e.displayText() = DB::Exception: Cannot parse expression of type Int64 here: '') (version 21.1.9.41 (official build))`

But when I cross check with the inserted object, I found all the value is already correct and when I convert it into SQL query to manually insert. it is succeed

![image](https://user-images.githubusercontent.com/20453210/139001969-40ff9bb7-986a-4b8f-9bf8-dddcc998f999.png)

## Steps to reproduce

1. I'm still tracking the cause and cannot explain how to reproduce the case.

## Expected behavior

Should be mapping correctly

## Actual behavior

Different error mentioned in jitsu log

**Comment by vklimontovich** [comment]
@absorbb please take a look and close if it could be solved with transformation

**Comment by absorbb** [comment]
@hamrio 
i recommend using JavaScript Transformation instead of Mapping (which is considered as deprecated): https://jitsu.com/docs/configuration/javascript-transform#overview
It helps to better understand what resulting event will look like.
Closing ticket. Please write a comment if you think that JavaScript Transformation  doesnt resolve the problem

**Comment by hamrio** [comment]
@absorbb 

actually I've tried with javascript transformation and it works. But, javascript transformation lead to higher memory and higher CPU compare to original mapping. Have you tried this? 


Thank you

**Comment by vklimontovich** [comment]
@hamrio oh, that's bad! Do you have more detailed info on CPU / memory consumption? We count on JS scripts as a main way to configure all things in Jitsu (including mappings).

If RAM is high that's probably a bug and can be fixed. CPU is a little bit trickier, however, we're switching to V8 (#746) which is much more efficient than [goja](https://github.com/dop251/goja) which is used at the moment

**Comment by hamrio** [comment]
@vklimontovich 

I've lost the screenshot and cannot post it here. When I tried to do javascript transformation (as I tried to adding prefix on the table), I received many Out Of Memory error from my server. It is increased 1 times more (previously, my server is only 200MB ram and after javascript transformation is around 400MB) and CPU is increase half times. CPU has no problem currently as my utilization hasn't reach 100%.

**Comment by absorbb** [comment]
@hamrio  Can you please try javascript transformation with 1.39.0? we have replaced javascript engine with v8.
It's hard to predict memory consumption in your case. it may go both ways.

**Comment by hamrio** [comment]
@absorbb 

as additional version info. 

Jitsu version : 
When Error : 1.37.3, now 1.40 and it is still error
Destination : 
Clickhouse version 21.1.9.41

**Comment by hamrio** [comment]
As disucssed with @absorbb this issue is clickhouse issue and this issue can be considered closed

**Comment by absorbb** [comment]
Issue mentioned be @hamrio is: https://github.com/ClickHouse/ClickHouse/issues/30383
