### ISSUE TITLE
Mixpanel Destination

### ISSUE THREAD

**Issue by mane87** [jitsucom/jitsu#642]
It would be great if Mixpanel would be added as a destination.

Use-case:
Currently we use a mix of Mixpanel and Google Analytics. We would love to log everything to JITSU and then forward relevant data to either Google Analytics, Mixpanel or both.

**Comment by scottccoates** [comment]
Not to hijack, but any chance Heap.io or GTM are on the docket?

**Comment by vklimontovich** [comment]
@scottccoates hope, but feel free to create a separate issue, it will be easier for us to track it.

BTW, Mixpanel destination code looks like this https://github.com/jitsucom/jitsu/blob/beta/server/templates/js/transform/mixpanel.js. The API is not final, but in a few weeks we're going to release an SDK that will allow 3rd-party developers to implement destinations for Jitsu as an npm package
