### ISSUE TITLE
Cant create a new batch snowflake destination

### ISSUE THREAD

**Issue by viggin543** [jitsucom/jitsu#649]
## Description

snowflake batch destination creation is broken
on jitsu:v1.37.1 ( latest version )
reproduced also on 1.37.0

## Steps to reproduce

enter jitsu UI
create new destination
select snowflake
select batch mode

## Expected behavior

configuration of snowflake destination as expected

## Actual behavior

application error
![image](https://user-images.githubusercontent.com/6231756/140643238-1522cf27-aaf5-4444-9c0f-d3a4297ac6a3.png)

- Existing snowflake destinations continue to work as expected
- Jitsu backend Logs have nothing interesting
-  no network errrs

- browser console contains the following errors + stack trace:

```
   TypeError: can't access property "_formData", cfg is undefined
    parameters snowflake.tsx:186
```

```
TypeError: can't access property "_formData", cfg is undefined
    displayForBatchOnly snowflake.tsx:56
```

![image](https://user-images.githubusercontent.com/6231756/140643473-4b668412-8b1b-461b-adde-2f31568bc4c6.png)

# its seems you forgot a full type safe accessor :) 
![image](https://user-images.githubusercontent.com/6231756/140643870-595b8cdd-e730-4a4d-80c8-267744ccbb5f.png)

- probably should be `?._formData`

**Comment by viggin543** [comment]
attempting to fix in https://github.com/jitsucom/jitsu/pull/650

**Comment by absorbb** [comment]
@viggin543 Thank you for the report and pr. I've applied fix but on the upper level. Fix already in beta docker images.
For now beta images differs from 1.37 only by this this fix. We will release a hotfix for release version tomorrow
