### ISSUE TITLE
Using custom Destination

### ISSUE THREAD

**Issue by thanhlmm** [jitsucom/jitsu#713]
### Problem

I want to use my own destination which is compatible with Airbyte, so I think it will be easy to add it to Jitsu

### Solution

Make a function to add new Airbyte destination

**Comment by vklimontovich** [comment]
We support only Airbyte sources. For destinations, we use our own engine/specification. 

What kind of destination you're looking to add? Maybe we have it already, or you can convert your code to our spec easily

**Comment by thanhlmm** [comment]
@vklimontovich do you have any doc to write destinations for Jitsu? I can't find it. 
I'm making a destination for [Streamr](https://streamr.network/) Here is airbyte version: https://github.com/devmate-cloud/streamr-airbyte-connectors

**Comment by vklimontovich** [comment]
Hi @thanhlmm! We do have SDK for destinations: https://github.com/jitsucom/jitsu-sdk. However, it's in alpha, meaning:
 - API is not 100% fixed
 - It's not tested to work with events coming from "pull" sources

However, Mixpanel destination is already based on this SDK. If you're adventurous enough, we're happy to collaborate on Streamr destination ) Please, ping me on [Jitsu Slack](https://jitsu.com) or email `vladimir at jitsu dot com`

**Comment by thanhlmm** [comment]
Great. I will ping you then
