### ISSUE TITLE
SDK auto-capture events 

### ISSUE THREAD

**Issue by azhard4int** [jitsucom/jitsu#714]
### Problem

What problem this feature is going to solve. Why this problem is important

Right now, we need to send the events manually by using `jitsu.track('event_name')`. It is difficult to keep track for the events that are added to product and there is always a chance some of the events are missed while developing new feature in the product.

### Solution

Proposed solution: architecture, implementation details etc

It would be really cool to have a feature where we can tell Jitsu to capture/track events automatically by using a boolean flag: `autoCapture`. 

If the flag is enabled, there are two options we can go with:

1. Keep track of events by using the html tags that are allowed: such as `button`, `a` etc.
2. Capture all clicked events and send to the Jitsu. (This is what Heap is doing: https://heap.io/product/autocapture)

What do you think of this, we can send a PR for this.

**Comment by lialzm** [comment]
Is there a plan for this feature?
