### ISSUE TITLE
Bulk upload Entity too large

### ISSUE THREAD

**Issue by thanhlmm** [jitsucom/jitsu#738]
## Environment

- **Deploy method**: docker-compose.yml
- **Jitsu version**:  for instance `1.38.4`
- **OS**: `Ubuntu 20.04` 
- **Cloud Provider**: time4vps

## Description
Upload 2mb file return
```
<body>
	<center>
		<h1>413 Request Entity Too Large</h1>
	</center>
	<hr>
	<center>nginx/1.21.4</center>
</body>
```

## Steps to reproduce
Using `/api/v1/events/bulk`
and this file

[demofile2.txt](https://github.com/jitsucom/jitsu/files/7797451/demofile2.txt)

## Expected behavior

I expected we can process a file about 10-50mb. But seem like the default max body in nginx is only 1MB

## Actual behavior

Entity too large error

**Comment by vklimontovich** [comment]
Hi @thanhlmm! Please see https://github.com/jitsucom/jitsu/releases/tag/v1.38.5

Unfortunately, I didn't find an easy way to make this configurable, so the payload limit is set to 200Mb. I hope that would be enough for most cases
