### ISSUE TITLE
Missing data when import via Bulk API and Big Query batch mode

### ISSUE THREAD

**Issue by thanhlmm** [jitsucom/jitsu#739]
## Environment

- **Deploy method**: docker-compose.yml
- **Jitsu version**:  `1.38.4`
- **OS**: `Ubuntu 20.04`
- **Cloud Provider**: time4vps

## Description
Missing data when import using Big Query destination in Batch mode

## Steps to reproduce
Call `/api/v1/events/bulk` to insert data
Data file: 
[demofile2.txt](https://github.com/jitsucom/jitsu/files/7797462/demofile2.txt)

## Expected behavior

It should insert with full data from event
<img width="1245" alt="Screen Shot 2022-01-01 at 14 44 59" src="https://user-images.githubusercontent.com/9281080/147846366-beee34ea-d8a8-4951-aea1-b392b3d5c160.png">
Stream mode has `data_metrics_market_data_ohlcv_last_1_hour_close` data

## Actual behavior
<img width="1232" alt="Screen Shot 2022-01-01 at 14 45 26" src="https://user-images.githubusercontent.com/9281080/147846375-fb364848-9c93-405c-ad3c-a35395aed639.png">
Batch mode without `data_metrics_market_data_ohlcv_last_1_hour_close`

**Comment by xtreding** [comment]
Hi @thanhlmm! I've noticed that original rows from the actual behavior screenshot in attached `demofile2.txt` don't have data under field `ohlcv_last_1_hour`. (there is `null` value under the key) `data_metrics_market_data_ohlcv_last_1_hour_close` column should be null as it is on actual behavior screenshot.
If you have any questions please let me know

**Comment by thanhlmm** [comment]
Hey it seems like my mistake. I'll close the case
