### ISSUE TITLE
BigQuery connection field with wrong name

### ISSUE THREAD

**Issue by FKrauss** [jitsucom/jitsu#740]
## Description
BigQuery is very confusing with this, `project-id` is super inconsistent. For the Jitsu connection to work, in Jitsu you need to put the `Project Number` in the field called `Project ID`

![image](https://user-images.githubusercontent.com/4820683/148356302-8acea0ba-b3f1-4880-8816-9491843a2afb.png)

GBQ has 3 different "identifiers": Project Name, Project Number and Project ID

![image](https://user-images.githubusercontent.com/4820683/148356206-b7f42489-7dcd-48e9-8abf-e3e575b9d76c.png)

In the past Project ID was the main thing you used to reference projects. But from about 2 years ago until now, the Number has been the main way to reference a project.

Jitsu's front-end can be fixed simply by changing the field name (as the error message when you try to connect already tells you to look for a 6 digit number, not a string ;) )

## Steps to reproduce

* create a BigQuery connection
* insert a Project ID [and all other parts of the form]
* test or save it
* Get an error message

## Expected behavior

Connection works

## Actual behavior

Project ID is said to be invalid and connection fails

## How to make it work

* On the `Project ID` field in Jitsu, insert Google's `Project Number` instead. 
* save
* it works

**Comment by xtreding** [comment]
Hi @FKrauss! Thank you for reporting the issue. Would you mind to attach BigQuery error message on test connection with Project ID?
