### ISSUE TITLE
s2s/events endpoint not documented

### ISSUE THREAD

**Issue by cymruu** [jitsucom/jitsu#743]
### Problem
There is `s2s/events` endpoint to enqueue events in batch but it is not mentioned in docs. Why? 

### Solution

Add docs for this endpoint.

Also I'd like to say thank you for all your hard work on this project 🙂

**Comment by xtreding** [comment]
Hi @cymruu! Thank you!
`s2s/events` endpoint is created for direct event collection from apps or backends. Documentation is [here](https://jitsu.com/docs/sending-data/api).

**Comment by cymruu** [comment]
@xtreding Thank you for your fast response. 
The docs you linked only describe only `s2s/event` endpoint. No word about `s2s/events/` to send in bulk

**Comment by vklimontovich** [comment]
Hi @cymruu! Thank you for giving us a heads up. I'm going to close this one since we have #394 which will result in generated API docs (including `s2s/events`)
