### ISSUE TITLE
Send custom event properties to Mixpanel

### ISSUE THREAD

**Issue by jboubix** [jitsucom/jitsu#750]
### Problem

Mixpanel destination curently recieves the *track* events but without any custom properties/payload.
The usability of Mixpanel is low without thoses properties.

### Solution

Proposal is to add the event payload to the Mixpanel Track ingestion endpoint payload in https://github.com/jitsucom/jitsu-mixpanel

**Comment by jboubix** [comment]
Yes definitly. How can I contribute to the new version ?

**Comment by absorbb** [comment]
@jboubix It is almost ready. We plan to release it next week. Your feedback will be welcome.

**Comment by vklimontovich** [comment]
@jboubix BTW, if you have any feedback and or suggestions, you can join or slack and DM me or @absorbb. We're happy to discuss our design for this feature and hear out your feedback: https://jitsu.com/slack
