### ISSUE TITLE
Sometimes jitsu server produces broken batch files

### ISSUE THREAD

**Issue by neracastle** [jitsucom/jitsu#756]
## Environment

- **Deploy method**: `built from sources`
- **Jitsu version**:  for instance `1.38.0`
- **OS**: for instance `Ubuntu 18.04`
- **Cloud Provider**: `Azure`

## Description
Sometime we see the next error in log "System error: Error parsing JSON file [...**.log] with events: invalid character '\x00' looking for beginning of value

## Steps to reproduce

Install JS-SDK to website and start tracking 'pageview' events

## Expected behavior

JSON event correctly created and sent to server

## Actual behavior

File with events can't be handled.

**Comment by vklimontovich** [comment]
Hey @neracastle, what is the destination, and what is the mode of destination (stream/batch?)

**Comment by neracastle** [comment]
> Hey @neracastle, what is the destination, and what is the mode of destination (stream/batch?)

Hi, destination is clickhouse. Mode is batch

**Comment by vklimontovich** [comment]
@neracastle did the whole batch fail, or only one record? Any chance you can identify this record in log file? (I believe that the file name is a part of error message)

**Comment by neracastle** [comment]
@vklimontovich it's batch fail. I tried to find the entry using `grep` but it didn't work. It looks like this - jitsu tries to read the file from the `incoming` directory, then parses the json. Parsing fails and jitsu skips this file

**Comment by vklimontovich** [comment]
Would you mind joining [our slack](https://jitsu.com/slack) and ping me? I guess it will be easier to track the issue via chat session

**Comment by xtreding** [comment]
Hi @neracastle! It occurred due to a system error while the Jitsu server shut down. We've added additional log rotation and fixed the system error shut down. This fix will be included in the next release (1.39) this week.

**Comment by neracastle** [comment]
Ok, thank you )
