### ISSUE TITLE
server.Dockerfile fails to build

### ISSUE THREAD

**Issue by authcompanion** [jitsucom/jitsu#774]
## Environment

- **Deploy method**: server.Dockerfile
- **Jitsu version**:  latest
- **OS**: for instance `Mac OS`
- **Cloud Provider**: fly.io

## Description
👋 Hi, Huge jitsu fan here -  creating the container img using the server.Dockerfile fails to build due to line 44 in the dockerfile - `make clean_js js` is missing from /server/Makefile.

**Comment by xtreding** [comment]
Hi @authcompanion! I've just committed a server.Dockerfile fix into the master branch. Do you use fly.io for building the server image?

**Comment by authcompanion** [comment]
Thank you vm!

Yes - fly.io deploys container images by either supplying them a dockerfile or container img -per: https://fly.io/docs/reference/builders/. Ideally, I'd like to try out your jitsucom/server:1.38.6 image w/ environment variables but, I couldn't get my jitsu server configuration to work after a number of trys.

**Comment by xtreding** [comment]
@authcompanion I've posted an update about your case in #778

**Comment by authcompanion** [comment]
ty @xtreding
