### ISSUE TITLE
Configuring jitsu server w/ Env Variables

### ISSUE THREAD

**Issue by absorbb** [jitsucom/jitsu#778]
### Discussed in https://github.com/jitsucom/jitsu/discussions/776

<div type='discussions-op-text'>

<sup>Originally posted by **authcompanion** January 27, 2022</sup>
Love the ability to configure jitsucom/server:1.38.6 via environment variables - this would simplify standalone deployments a lot. Really nice addition here https://jitsu.com/blog/jitsu-1.38#improved-docker-images

Unfortunately, I've been running into repeated server configuration errors - getting 'invalid token' errors when authenticating with a client_secret. 

I'm passing raw json to API_KEYS_URL like such - 

```
{
    "tokens": [
        {
            "id": "myid",
            "client_secret": "secret1",
            "server_secret": "secret2"
        }
    ]
}
```
It makes me wonder if this env variable API_KEYS_URL can really take raw json instead of a URL. 

Would you have a working example of jitsucom/server:1.38.6 being configured with env variable using CLUSTER_ADMIN_TOKEN, API_KEYS_URL, DESTINATIONS_URL (postgres)? 

</div>

**Comment by xtreding** [comment]
Hi @authcompanion! Thank you for reporting. It's a bug and we are going to fix it in the next release (hopefully next week).
If you need to send events only from web (you need only client secret) then you can use a workaround now - just provide a client secret as a single string into the `API_KEYS_URL` env var. 

For example:

```
docker run -p 8001:8001 -e API_KEYS_URL='secret1' -e DESTINATIONS_URL='{"destinations":{"<destination_id>": { ... }}}' jitsucom/server:1.38.6
```
