### ISSUE TITLE
Adding Sendinblue integration

### ISSUE THREAD

**Issue by absorbb** [jitsucom/jitsu#779]
### Discussed in https://github.com/jitsucom/jitsu/discussions/737

<div type='discussions-op-text'>

<sup>Originally posted by **SAVE-POlNT** December 24, 2021</sup>
Hello , great product here btw
im addicted to finding new Dev tools in general
and as a data persone 
jitsu , airbyte and n8n are the best OSS service connectors , but i do not know why all of them don't have a connector to one of the most used CRMS (sendinblue) it is easy to interact with.
it will be great if someone can help me make this possible 
i don (t know much about jitsu but i think it uses airbyte connectos so maybe making this for airbyte will make it available for jitsu ?</div>

**Comment by stouch** [comment]
I was looking for this integration too.
