### ISSUE TITLE
Error executing airbyte check

### ISSUE THREAD

**Issue by fdaugs** [jitsucom/jitsu#797]
## Environment

- **Deploy method**: `jitsucom/jitsu docker`
- **Jitsu version**:  for instance `1.39.1`
- **OS**: `Ubuntu 20.04`
- **Cloud Provider**: `AWS EC2`

## Description
I deployed jitsu and followed the guide at: https://jitsu.com/docs/deployment/deploy-with-docker/joint-image
When I try to add an airbyte based destination I can enter the credentials (Step 1 Configuration) but when I navigate to the next step, I get the following error: 

```
[ERROR]: [response] "/api/v1/sources/test" error: {"message":"Error executing airbyte check:\n\t{\"type\": \"LOG\", \"log\": {\"level\": \"FATAL\", \"message\": \"[Errno 2] No such file or directory: '/tmp/airbyte/8578702ad5c54dbfa13fe9ea136aa7cf/79ae87f342504817bea65aa5f0132eff.json'\\nTraceback (most recent call last):\\n File \\\"/airbyte/integration_code/main.py\\\", line 13, in \u003cmodule\u003e\\n launch(source, sys.argv[1:])\\n File \\\"/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py\\\", line 127, in launch\\n for message in source_entrypoint.run(parsed_args):\\n File \\\"/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py\\\", line 80, in run\\n self.configure_sentry(source_spec.connectionSpecification, parsed_args)\\n File \\\"/usr/local/lib/python3.7/site-packages/airbyte_cdk/entrypoint.py\\\", line 67, in configure_sentry\\n config = self.source.read_config(parsed_args.config)\\n File \\\"/usr/local/lib/python3.7/site-packages/airbyte_cdk/connector.py\\\", line 42, in read_config\\n with open(config_path, \\\"r\\\") as file:\\nFileNotFoundError: [Errno 2] No such file or directory: '/tmp/airbyte/8578702ad5c54dbfa13fe9ea136aa7cf/79ae87f342504817bea65aa5f0132eff.json'\"}}\n\n\texit status 1","error":""} from: IP_ADRESS method: POST
``` 
(This one is from the container logs but it is also shown in the ui)

The logs contain some more errors, that might be helpful:
```
2022-02-05 17:29:37 [ERROR]: source-hubspot-0.1.38-226f868c-7fc0-4972-82f3-ac35647e029f airbyte runner closing failed. Killing. Closing error: exit status 1
```

```
2022-02-05 17:29:30 [ERROR]: [response] "/api/v1/sources/test" error: 404 page not found
```

**Comment by vklimontovich** [comment]
Would you mind providing a list of env variables and mounted volumes? It will help us to diagnose the issue

**Comment by fdaugs** [comment]
Sure.

This is the list of ENVs:
```
USER_RECOGNITION_ENABLED=false
REDIS_URL=*CONNECTION_STRING*
CLUSTER_ADMIN_TOKEN=*RANDOM_TOKEN*
```

I've only mounted the following volumes:
```
/var/run/docker.sock:/var/run/docker.sock
jitsu_workspace:/home/eventnative/data/airbyte
```

**Comment by vklimontovich** [comment]
Seems like the correct configurations. 

@xtreding, @absorbb - I suspect that's connector-specific. All connectors should use only `jitsu_workspace` to write data to disk. Either of the following should work:
 - Before running sync, set env `TMPDIR` to `/home/eventnative/data/airbyte/tmp-{syncId}`
 - Make sure that `/tmp/` is writeable

@fdaugs, it should be resolved in couple of days

**Comment by fdaugs** [comment]
Thanks. I tried several different Airbyte connectors butnone of them worked.

**Comment by xtreding** [comment]
Hi @fdaugs! Would you mind to upgrade Jitsu to `1.39.2`? 
You can do it just for running a new Jitsu docker container: 

```
docker run -e USER_RECOGNITION_ENABLED=false -e CLUSTER_ADMIN_TOKEN=<YOU_TOKEN> -e REDIS_URL=<YOUR_CONNECTION_STRING> -v /var/run/docker.sock:/var/run/docker.sock -v jitsu_workspace:/home/eventnative/data/airbyte jitsucom/jitsu:1.39.2
```

Please check that `/home/eventnative/data/airbyte` is mounted to the exact `jitsu_workspace` volume. 
After running, try to create hubspot source. So if there is a error, you can easily find a log message in docker logs.

**Comment by fdaugs** [comment]
Hi @xtreding,

Thank you again for the quick support and the great project! I tried this again and didn't work, so I investigated further and notices, that the cause was actually a configuration issue.

I host jitsu on ECS and used a [Bind mount](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/bind-mounts.html) instead of a [Docker volume](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/docker-volumes.html) for the jitsu_workspace volume. So a docker volume with the name "jitsu_workspace" was never created.  I fixed this and it works now.

**Comment by xtreding** [comment]
Hi @fdaugs,

Thank you for the information. We've added `jitsu_workspace` volume check - there will be a log message about the status of mounted volume is it correct or not. Fix is currently in `beta`. We're going to release it this week.

**Comment by fdaugs** [comment]
That is a great Idea! Meaningful error messages are always very helpful.
