### ISSUE TITLE
Move javascript evaluation to separate runtime

### ISSUE THREAD

**Issue by absorbb** [jitsucom/jitsu#808]
### Problem

Running v8 in the main process is not safe.
v8 prone to crashes, e.g. in OOM case - and when v8 crashes main process crashes

### Solution

We need to evaluate javascript in the separate process.

Interface:
- Loads raw code or npm plugin
- Expose exported symbols
- Execute exported function by name

There are several option:
process: 
1. per destination
2. per instance

communicate: 
1. stdin/stdout.
2. socket or domain socket
3. http
4. grpc

language:
1. typescript (node.js executable)
2. rust (deno v8 runtime or deno itself)
3. go

**Comment by vklimontovich** [comment]
A few thoughts on interface design.

### Command Line tool

Assuming we'll go with stdin / stdout approach, I believe following CLI will make sense

#### Source params

These params will define the source of JS code

```
--npm-name <packageName>
--npm-version <versionSpec>
--npm-url, --npm-credentials (for private repos, can skip the implementation right now)
--format cjs (we don't need to support anything except CommonJS now)

or

--std-in (read code from stdin, two line breaks should indicate end of input)   
```

Once the source code is read, it should be internally represented as set of symbols. Symbol can be either `value` or `function`. In case of CJS, those symbols are just exported functions / costs. If the code is read from stdin, the only symbol should be `main` (type of function)

Once the code is loaded, the parent process should communicate with it with messages sent to stdin. Each message should be JSON as a single line where `\n` indicates the end of the message. The response should be JSON one-liner too.

Here's the list of messages:

**Describe Message**

```
{"messageType": "describe"}
```

Response:
```
{
  "symbols": [
      {"symbol": "descriptor", "type": "value", "value": {...}},
      {"symbol": "validate", "type": "function"}
  ]
}
```

**Run Message**

```
{
   "messageType": "run",
   "function": "validate",
   "args": [...]
}
```

Response:
```
{
  "status": "error" or "ok",
  "errorMessage": "message",
  "logMessages": [{"severity": "", "string"}]  //log messages from console.log
  "errorDetails": "stacktrace or similar"

//or (if status is ok)

  "result": {...}
}
```

Please note, that if symbol returns Promise, the tool should wait for it to be resolved and return final status

### Go wrapper

The go wrapper should follow same interface as CLI. See pseudo-code (TypeScript, really)

```typescript
export type ScriptSymbol = {
  type: 'function' | 'value'
  value?: any
}

export type ExecResult = {
  status: "ok" | "error"
  logMessages: {severity: string, content: string}[]
  result?: any
  errorMessage?: string
  errorDetails?: string
}

interface Script {
  describe(): Record<string, Symbol>
  exec(symbol: string, args: any[]): ExecResult
}

export type NpmSpec = {
  npmPackage: string
  npmVersion: string
  repoUrl?: string
  repoCredentials?: string
}

export type ScriptFactory = (
  npmSpec?: NpmSpec,
  code?: string
) => Script
```

`Script` should handle the restarts internally. If underlying process has crashed, it should spawn a new one.

### Builtins (open question)

We need to find a way how to pass 'builtins' — a number of functions that are predefined.
