### ISSUE TITLE
Support of SSO via BoxyHQ layer

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#812]
We need to support SSO login via [BoxyHQ](https://boxyhq.com/) OAuth → SAML proxy. The implementation should lay ground for future SSO provider integration, however at the moment we should be focused on getting BoxyHQ integration working.

## Requirements

As a result of this issue, users should be able to config BoxyHQ for self-hosted Jitsu Configurator instances (via env var, or config). If the configuration is provided, the button `Continue with SSO` should appear under login button.

So far we don't need to create a new user account if auth is successful, but the account doesn't exist

## Tech details.

The feature should be configurable via `SSO_CONFIG` variable which contains JSON:

```
{
    "provider": "boxyhq",
    "url": "..."
    "tenant": "..."
    "product": "..."
    "client_secret"
}
```

Also, it should be possible to configure SSO within configurator.yaml keeping the same structure.

## Links

[1] - BoxyHQ documentation: https://boxyhq.com/docs/jackson/saml-flow#3-oauth-20-flow

**Comment by Flyover-ArtSk** [comment]
@vklimontovich we already have different providers for authorization.
Example for cloud (configurator.yaml):
```
auth:
  firebase:
    project_id: 
    credentials_file:
  admin_domain: 
  admin_users:
```
I can create new boxyhq auth provider similar to the firebase provider and use it there.
