### ISSUE TITLE
Events cache: keep entities errors separately

### ISSUE THREAD

**Issue by absorbb** [jitsucom/jitsu#823]
### Problem

Errors often get replaced from events cache with new events - so it is hard for clients to notice them and to react.

### Solution

- ✅ Introduce separate collections for errors only: by token and by destination.
- ✅ For token store parsing errors (see #822) with bad events payload (trim payload to some limit e.g. 10kb)
- ✅ Use rate limiter to collect errors (same as in #766)
- ✅In UI show cached errors in Statistics page of each destinations
- ✅For token introduce  Statistics page with token level metrics plot (like in #822) and errors block

**Comment by taletski** [comment]
Took over this task to implement the following:

- [ ] Add the "Latest Logs" button to the destination editor, it should redirect to the tasks logs page with filters on to show logs for the destination;
- [ ] "Live Events" button in Statistics Page should redirect user to the events by the API Key that was chosen in the UI;
- [ ] Add a hint about errors happened within the last month to the tasks logs page;
- [ ] API Keys should provide the same UI with statistics charts that Destinations and Sources already do;
