### ISSUE TITLE
API error trying to add Facebook Marketing source

### ISSUE THREAD

**Issue by lpadula** [jitsucom/jitsu#831]
## Environment

- **Deploy method**: docker-compose.yml
- **Jitsu version**:  for instance `1.37.5`
- **OS**: Ubuntu 20.04 server
- **Cloud Provider**: Hetzner
- **Docker Params (if deployed with docker)**: none

## Description
Facebook source get API error.

## Steps to reproduce

Go to Sources -> Add source -> Facebok Marketing and then complete form fields.

## Expected behavior

Source added without errors.

## Actual behavior

Get an error:

general: facebook: (#2635) You are calling a deprecated version of the Ads API. Please update to the latest version: v13.0. (code: 2635; error_subcode: 0, error_user_title: , error_user_msg: ) (#400)

**Comment by absorbb** [comment]
Hi @lpadula 
Thank you for reporting that.
Fixed in [1.40.0](https://jitsu.com/blog/jitsu-1.40)
