### ISSUE TITLE
Automatically update facebook API version

### ISSUE THREAD

**Issue by absorbb** [jitsucom/jitsu#833]
### Problem

Facebook often upgrade API version without breaking compatibility.
Nonetheless previous API endpoint stops working

### Solution

Find a way to detect current version of Facebook API
Introduce service that starts once facebook source or destination added to instance.
Service periodically (e.g. Once a day) get latest version of Facebook API
`facebook_marketing.go` and `facebook_conversion_api.go` uses this version instead of hardcode

**Comment by jfk9w** [comment]
Facebook source will be implemented with JS `jitsu-sdk`, so we'll postpone the issue till then.
