### ISSUE TITLE
Google Ads OAuth fails with "general: 'developer token' is required. (#400)"

### ISSUE THREAD

**Issue by fdaugs** [jitsucom/jitsu#834]
## Environment

- **Deploy method**: for instance `jitsucom/jitsu docker`
- **Jitsu version**:  for instance `1.39.3`
- **Cloud Provider**: for instance AWS ECS
- **Docker Params (if deployed with docker)**: a list of env variables with values (please, hide sensitive credentials!), mapped volumes and ports

## Description
Connecting the Google Ads source with OAuth Credentials (refresh token optained vie cli) fails with: `general: 'developer token' is required. (#400)`

## Steps to reproduce
Add Google Ads source with OAuth Credentials

**Comment by absorbb** [comment]
Hi @fdaugs 
Google Ads requires to obtain developer token for each app to have access to Google Ads API:
https://developers.google.com/google-ads/api/docs/first-call/dev-token
Once obtained you need to add it to server's config file `eventnative.yaml`
```yaml
google_ads:
  developer_token: Abc123
 ```
 Its is our oversight that information about developer_token is not mentioned in UI and documention - we are going to fix that. Thank you for making this ticket.
 
 If it is not possible to obtain  Google Ads developer token i suggest using cloud version of jitsu [cloud.jitsu.com](https://cloud.jitsu.com)

**Comment by fdaugs** [comment]
Hi @absorbb,

thanks for your quick response! I think it should be possible for me to obtain the developer token.
As of now I use the UI to configure my sources and not the eventnative.yaml. Editing this file would require me to either mount  this file to the docker container and manage it on the host system or building my own docker image. I would like to avoid both. 

I think a good option would be to expose this setting in the UI, like its done in the Google Adwords source, and/or include the "Google Ads" Airbyte connector.

**Comment by absorbb** [comment]
> I think a good option would be to expose this setting in the UI, like its done in the Google Adwords source, and/or include the "Google Ads" Airbyte connector.
We will do that as part of this ticket.

You can also add environment variable to your docker run command, to avoid editing eventnative.yaml:
`-e GOOGLE_ADS_DEVELOPER_TOKEN=Abc123`

**Comment by fdaugs** [comment]
Ah awesome! That's solves the problem! Thank you!
