### ISSUE TITLE
Destination and Source not display on configurator when using eventnative.yaml

### ISSUE THREAD

**Issue by badgeek** [jitsucom/jitsu#859]
## Environment

- **Deploy method**: docker-compose.yml
- **Jitsu version**:  v1.40.2
- **OS**: ubuntu-s-1vcpu-1gb-sgp1-01 5.4.0-84-generic- 
- **Cloud Provider**: Digitalocean

## Description
Destination and Source not display on configurator when using eventnative.yaml

## Steps to reproduce
im using eventnative.yaml, took it from benchmark example yaml and added custom postgres and jira source and destination

## Expected behavior

source and destination from eventnative.yaml will be shown on configurator

## Actual behavior

source and destination is default when installing configurator at firstt time

**Comment by skynet2** [comment]
Hi, 
Any update on that? I have the same issue on the latest 1.43.6.

I mounted my custom eventnative.yaml with my own sources and destination, but once I go to /configurator, I don't see my setup.

Also, when I go to "download config", I see 
![image](https://user-images.githubusercontent.com/3065048/221443919-fa15d033-3d49-4c39-9e33-c61ec2d444e0.png)
which is not part of my config.

here is list of my env variables
```    - env:
        - name: REDIS_URL
          value: 'redis://redis.infra.svc.cluster.local:6379'
        - name: CONFIGURATOR_ADMIN_TOKEN
          value: 123
        - name: SERVER_ADMIN_TOKEN
          value: 123
        - name: TLS_SKIP_VERIFY
          value: 'true'
        - name: DOCKER_HOST
          value: 'tcp://localhost:2375'
        - name: SERVER_VOLUMES_WORKSPACE
          value: /tmp/airbyte/
```
