### ISSUE TITLE
Repeated eventn_ctx_event_id with Bing Ads source.

### ISSUE THREAD

**Issue by icychocolate98** [jitsucom/jitsu#929]
Good morning,

I think I found an issue with Bing Ads source, when I'm trying to download aggregated reports (daily) it seems that there is a problem with column `eventn_ctx_event_id`. It repeats the same `eventn_ctx_event_id` depending on `"devicetype" `and if it let Jitsu create automatically the tables it overrides my events due to `ReplacingMergeTree` engine.

I solved it temporarily by creating the tables manually with `MergeTree` engine (will be a problem if I run full-refresh later) and it works fine, but every row groupped by "`devicetype`" has the same "`eventn_ctx_event_id`".

As you can see here, this events should have different eventn_ctx_event_id but they have the same depending on decivetype.
![image](https://user-images.githubusercontent.com/45860726/169258051-c6097b36-c52f-4c9c-98aa-922a4143d6b2.png)

Adding campaignid to Group By clause:
![image](https://user-images.githubusercontent.com/45860726/169256859-0d8636c2-a491-4a65-9e2a-cca3a888d53a.png)

I hope this helps!

**Comment by absorbb** [comment]
We generate `eventn_ctx_event_id` based on primary keys fields provided by source.
In case of Bing - it is airbyte implementation.
Bing Airbyte Source currently returns the following set of key fields for reports stream:
```["TimePeriod", "Network", "DeviceType"]```
which misses the main entity id like 
```"Campaing ID"```

I’ve created a bug report in airbyte repository:
https://github.com/airbytehq/airbyte/issues/13032
