### ISSUE TITLE
Add elasticsearch as a data warehouse

### ISSUE THREAD

**Issue by isaiahdahl** [jitsucom/jitsu#934]
### Problem

I want to be able to stream events into an elasticsearch indexes so I can use [Kibana](https://www.elastic.co/kibana/) for BI visualizations. 

### Solution

Add elasticsearch as a destination where how you connect is much like Clickhouse or Snowflake.

Not sure if more detail on this request is required. Seems pretty straightforward.

**Comment by vklimontovich** [comment]
The easiest way to implement that is to make a [destination plugin](https://jitsu.com/docs/extending/destination-plugins) that sends data to Elastic via [REST API](https://www.elastic.co/guide/en/elasticsearch/reference/current/rest-apis.html). Unfortunately, we don't have a capacity to develop this plugin by ourselves, but you're welcome to do so if you have time! We'll add a link to your npm package to UI

**Comment by donavan-tangible** [comment]
I'm currently working on it.
