### ISSUE TITLE
Destinations get disconnected when editing and saving source in GUI

### ISSUE THREAD

**Issue by simple10** [jitsucom/jitsu#939]
## Environment

This is happening in the hosted version on cloud.jitsu.com

I have not confirmed if it's also an issue with the self-hosted version.

Browser: Chrome (latest) on Mac. Have not confirmed other browsers.

## Description

Editing a JS Events source in the GUI **without modifying the destinations field** causes the destinations to get disconnected. Re-editing and adding back the destinations works.

The destinations are being properly populated in the Connected Destinations field when editing a source. But upon saving without modifying the destinations, the destinations are disconnected.

Modifying the Connected Destinations field and saving the source works. 

## Steps to reproduce

In GUI at cloud.jitsu.com:

1. Click on JS Events Source
2. Click save without modifying anything **OR** change HTTP Origins and click save 
3. Click on Home to view Sources / Destinations: sources and destinations are now disconnected
4. Click on the Source again
5. Add back the destinations
6. Click save
7. Click Home; sources and destinations are reconnected

## Expected behavior

The destinations shown in Connected Destinations field should stay connected upon saving the source.

**Comment by absorbb** [comment]
Fixed in 1.42
