### ISSUE TITLE
Jitsu-cli extension create error: Cannot find module ‘JSON5’ 

### ISSUE THREAD

**Issue by AlgoSolu** [jitsucom/jitsu#943]
## Environment
- Centos 

## Description
Cannot run command "npx jitsu-cli extension create --type destination"
error: Cannot find module ‘JSON5’ 

## Steps to reproduce
N/A

## Expected behavior
Run command "npx jitsu-cli extension create --type destination"

## Actual behavior
<img width="1172" alt="capture_d___e__cran__le_2022-05-29_a___12 30 19" src="https://user-images.githubusercontent.com/7544240/171240723-c453552b-0b58-47f5-86d8-e25499a090e1.png">

**Comment by vklimontovich** [comment]
I published a small fix - `0.7.4`. Would you please try with `npx jitsu-cli@0.7.4`

**Comment by AlgoSolu** [comment]
it work thanks
