### ISSUE TITLE
Errors in some subjects in example templates on Google Ads source - v1.42.2

### ISSUE THREAD

**Issue by icychocolate98** [jitsucom/jitsu#947]
## Environment

- **Jitsu version**: 1.42.2
- **OS**: KDE neon User - 5.24

## Description
2 days ago, I have noticed an error for stop using v8 in Google Ads source because it's deprecated, moreover when I set up (correctly) Google Ads source, some subjects fails due to some fields incomaptibility with this new version.

Subjects where I found errors are: "campaigns" and ""ad_group_ad"

## Steps to reproduce

1. Connect Google Ads source
2. Sync data
3. Watch "campaigns" and "ad_group_ad" fail.

## Expected behavior

Sucess status on campaigns and ad_group_ad subjects.

## Actual behavior

Error status on campaigns and ad_group_ad subjects.

**Comment by absorbb** [comment]
@icychocolate98 
If Google changed available fields for some resources Jitsu cannot do much about that.
I recommend to rebuild field list using query builder:
https://developers.google.com/google-ads/api/fields/v11/campaign_query_builder
