### ISSUE TITLE
Source as S3 fails with "only single character unicode strings can be converted to Py_UCS4"

### ISSUE THREAD

**Issue by programmeddeath1** [jitsucom/jitsu#953]
## Environment

- **Deploy method**: `docker-compose.yml`
- **Jitsu version**:  latest
- **OS**: for instance `Ubuntu 21.04`
- **Cloud Provider**: local

## Description
Tried to connect jitsu source as S3 bucket file. It is able to connect properly but the stream creation fails with 
```
  File "/airbyte/integration_code/source_s3/source_files_abstract/formats/csv_parser.py", line 157, in stream_records
    pa.csv.ParseOptions(**self._parse_options()),
  File "pyarrow/csv.pyx", line 235, in pyarrow._csv.ParseOptions.init_
  File "pyarrow/csv.pyx", line 299, in pyarrow._csv.ParseOptions.escape_char.set_
  File "pyarrow/_csv.pyx", line 43, in pyarrow._csv._single_char
ValueError: only single character unicode strings can be converted to Py_UCS4, got length 0
```

Selected source as an S3 bucket file. The destination is a postgresql setup locally.
## Expected behavior
It should connect and start data stream

## Actual behavior
It fails with above given error.

Though jitsu uses airbyte connectors for S3, I ran the same architecture on airbyte directly and it was able to connect and stream from the S3 bucket to the postgresql database.
It was running on te airbyte docker setup locally, so this seems like a jitsu issue.

**Comment by absorbb** [comment]
Fixed in [1.42.3](https://github.com/jitsucom/jitsu/releases/tag/v1.42.3)
