### ISSUE TITLE
CSV not escaping `\`  ( backslash ) 

### ISSUE THREAD

**Issue by viggin543** [jitsucom/jitsu#957]
## Environment

- **Deploy method**: `k8s GKE`
- **Jitsu version**:  `1.42.2`
- **OS**: for instance `GKE os`
- **Cloud Provider**:   `GCP`
- - **Destination**:   `snowflake batch`

## Description
Jitsu fails to escape `\` character in csv column values.

We had an incident where CSV files failed to load to snowflake. 
we discovered that a value ended in a backslash character `\`
So in the CSV file, it looked like this:

```
,somevalue\,anothervalue
```
notice the backslash at the end of `somevalue`

this causes the CSV to be corrupt since it escapes the following comma `,` and shifts all the columns to the left.

While opening the bad CSV file with Numbers or Excel those tools had no problem with this edge case.

It's probably a minor fix.
I Would be happy to try to do it if you could direct me to the code that writes the CSV files and handles escaping stuff.

## Steps to reproduce

send data to  jitsu . End a value with a backslash. The CSV file will be corrupt.

## Expected behavior

CSV file should escape the backslash

## Actual behavior

Its not escaped

**Comment by absorbb** [comment]
@viggin543 Fix is already on the `beta` image tag. Will be released as a hotfix release at the beginning of the next week

**Comment by absorbb** [comment]
Fixed in [1.42.4](https://github.com/jitsucom/jitsu/releases/tag/v1.42.4)
