### ISSUE TITLE
Full refresh for Singer, Airbyte and Go native sources

### ISSUE THREAD

**Issue by vklimontovich** [jitsucom/jitsu#958]
## Problem

At the moment, full refresh for subj doesn't work well. It first truncates table, and then starts to fill table once again. It means that during the run data is inconsistent.

## Solution

We have a mechanism for transactional full refresh which we use in [Jitsu SDK backed sources](https://github.com/jitsucom/jitsu-sdk). We should utilize same thing for all other types of sources.

Cleanup deprecated tables.

**Comment by trigo-darad** [comment]
Is there any workaround?
