### ISSUE TITLE
[Amplitude] Allow to specify the endpoint url (Standard / EU)

### ISSUE THREAD

**Issue by smalot** [jitsucom/jitsu#960]
### Problem

In order to respect GDPR compliancy, Amplitude has recently created a EU implementation of its platform.
By the way, this new platform is accessible throught a dedicated endpoint

* Standard Server	https://api2.amplitude.com/2/httpapi
* EU Residency Server	https://api.eu.amplitude.com/2/httpapi

@see : https://www.docs.developers.amplitude.com/analytics/apis/http-v2-api/#endpoints

### Solution

Add a select field in the Amplitude setup screen to choose the right endpoint, with a default value matching the "Standard Server".

**Comment by absorbb** [comment]
Fixed in [v1.42.5](https://github.com/jitsucom/jitsu/releases/tag/v1.42.5)
