### ISSUE TITLE
Hubspot destination createOrUpdate event skipped despite Transforms 

### ISSUE THREAD

**Issue by nandanrao** [jitsucom/jitsu#966]
## Environment
Jitsu Cloud

## Description
I understand from the documentation (https://jitsu.com/docs/destinations-configuration/hubspot) that an event will be sent as a createOrUpdate event to the /contacts API if, after Transforms are applied, the `event_type` is "user_identify" and there is a `user` property which is an object with properties such as `email`.  

However, my custom events that come in from the /events API, do not have an "event_type" property, but get one added via Transforms, are skipped and not sent onward to this destination. 

## Steps to reproduce

1. Create a set of keys and post an event to `https://t.jitsu.com/api/v1/s2s/event` that does not have "event_type" or "user" properties. 
2. Connect Hubspot as a destination for events from that set of keys. 
3. Note that the event is skipped, as expected. 
4. Add Transforms to add `event_type: "user_identify"` and `user` properties. 

## Expected behavior

I expected that upon adding `event_type: "user_identify"` and `user` properties, the event would be sent onward to Hubspot, as events from the js sdk, for example.

## Actual behavior

The event is skipped.

**Comment by absorbb** [comment]
Fixed in [1.42.8](https://github.com/jitsucom/jitsu/releases/tag/v1.42.8)
