### ISSUE TITLE
Failed to inspect current docker container by containerID when initializing airbyte

### ISSUE THREAD

**Issue by sashayakovtseva** [jitsucom/jitsu#973]
## Environment

- **Deploy method**: `jitsucom/server docker`
- **Jitsu version**:  `v1.43.0`
- **OS**: for instance `Mac OS Monterey`
- **Cloud Provider**: running locally on `Darwin 21.6.0 Darwin Kernel Version 21.6.0: Wed Aug 10 14:28:35 PDT 2022; root:xnu-8020.141.5~2/RELEASE_ARM64_T8101 arm64`

## Description
Hello!
I am getting started with jitsu locally. I've noticed that there might be an issue with the latest v1.43.0 release. v1.42.8 works fine.

## Steps to reproduce

- launch standalone jitsu v1.43.0 with any airbyte source

## Expected behavior

- airbyte integration is initialized

## Actual behavior

- airbyte integration initialization fails with error `Airbyte integration is disabled: failed to inspect current docker container by containerID [/]: json: cannot unmarshal array into Go value of type types.ContainerJSON`

**Comment by absorbb** [comment]
Hi @sashayakovtseva 
I've re-uploaded  v1.43.0 image with fix.
Please refresh you image with `docker pull jitsucom/server:latest` or `docker pull jitsucom/server:1.43.0` depending on which tag you use to run Jitsu
and try again

**Comment by sashayakovtseva** [comment]
I confirm it works now
