### ISSUE TITLE
DateTime type string parsing error when transfer data from mysql to clickhouse

### ISSUE THREAD

**Issue by zzwy2018** [jitsucom/jitsu#978]
## Environment

- **Deploy method**: `docker-compose.yml` 
- **Jitsu version**:  for instance `1.42.8`
- **OS**: `CentOS 7.9`
- **Cloud Provider**: ' Aliyun`
- **Docker Params (if deployed with docker)**: a list of env variables with values (please, hide sensitive credentials!), mapped volumes and ports
- ** Airtyte Image version: 1.0.12
- 
## Description
DateTime type string parsing error when transfer data from mysql to clickhouse

## Steps to reproduce

1) Configure a source connector with type mysql and the connection test pass (Airtyte Image version: 1.0.12)
2) Configure a destination connector with type clickhouse and the connection test pass
2) Sync with above connectors.

## Expected behavior

The configured database data from mysql source can be trasferred to clickhouse destination

## Actual behavior

Task failed with DateTime type string parsing error as following:

2022-11-13 00:00:10 [ERROR] - Airbyte output line process error: Error storing 1 source objects in [c8unt33cma7eedtwruf3mr.osupwy23lamqg4q3658hi] destination: report.sql.execute_insert_in_batch: failed to execute insert {db_info: 
database: jira_local_mysql_jitsu_1021
table: mysql_cwd_directory
statement: INSERT INTO "jira_local_mysql_jitsu_1021"."mysql_cwd_directory" ("_timestamp", "active", "created_date", "description", "directory_name", "directory_position", "directory_type", "eventn_ctx_event_id", "id", "impl_class", "lower_directory_name", "lower_impl_class", "src", "updated_date") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
values of 1st object: {"_timestamp": 2022-11-13 00:00:10.209813 +0000 UTC, "active": 1, "created_date": 2013-02-28T11:57:51.000000, "description": SmlyYSBkZWZhdWx0IGludGVybmFsIGRpcmVjdG9yeQ==, "directory_name": SmlyYSBJbnRlcm5hbCBEaXJlY3Rvcnk=, "directory_position": 0, "directory_type": SU5URVJOQUw=, "eventn_ctx_event_id": 77529b68d130d125ff07a534a7b69adb, "id": 1, "impl_class": Y29tLmF0bGFzc2lhbi5jcm93ZC5kaXJlY3RvcnkuSW50ZXJuYWxEaXJlY3Rvcnk=, "lower_directory_name": amlyYSBpbnRlcm5hbCBkaXJlY3Rvcnk=, "lower_impl_class": Y29tLmF0bGFzc2lhbi5jcm93ZC5kaXJlY3RvcnkuaW50ZXJuYWxkaXJlY3Rvcnk=, "src": source, "updated_date": 2013-02-28T11:57:51.000000}
}, cause: Code: 6, Message: Cannot parse string '2013-02-28T11:57:51.000000' as DateTime: syntax error at position 19 (parsed just '2013-02-28T11:57:51'): while executing 'FUNCTION if(isNull(_dummy_0) : 3, defaultValueOfTypeName('DateTime') :: 2, _CAST(_dummy_0, 'DateTime') :: 4) -> if(isNull(_dummy_0), defaultValueOfTypeName('DateTime'), _CAST(_dummy_0, 'DateTime')) DateTime : 1': While executing ValuesBlockInputFormat. Process will be killed
2022-11-13 00:00:10 [ERROR] - Error closing airbyte runner: exit status 1
2022-11-13 00:00:10 [INFO ] - Config saved.
2022-11-13 00:00:10 [ERROR] - Error synchronization: Error storing 1 source objects in [c8unt33cma7eedtwruf3mr.osupwy23lamqg4q3658hi] destination: report.sql.execute_insert_in_batch: failed to execute insert {db_info: 
database: jira_local_mysql_jitsu_1021
table: mysql_cwd_directory
statement: INSERT INTO "jira_local_mysql_jitsu_1021"."mysql_cwd_directory" ("_timestamp", "active", "created_date", "description", "directory_name", "directory_position", "directory_type", "eventn_ctx_event_id", "id", "impl_class", "lower_directory_name", "lower_impl_class", "src", "updated_date") VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)
values of 1st object: {"_timestamp": 2022-11-13 00:00:10.209813 +0000 UTC, "active": 1, "created_date": 2013-02-28T11:57:51.000000, "description": SmlyYSBkZWZhdWx0IGludGVybmFsIGRpcmVjdG9yeQ==, "directory_name": SmlyYSBJbnRlcm5hbCBEaXJlY3Rvcnk=, "directory_position": 0, "directory_type": SU5URVJOQUw=, "eventn_ctx_event_id": 77529b68d130d125ff07a534a7b69adb, "id": 1, "impl_class": Y29tLmF0bGFzc2lhbi5jcm93ZC5kaXJlY3RvcnkuSW50ZXJuYWxEaXJlY3Rvcnk=, "lower_directory_name": amlyYSBpbnRlcm5hbCBkaXJlY3Rvcnk=, "lower_impl_class": Y29tLmF0bGFzc2lhbi5jcm93ZC5kaXJlY3RvcnkuaW50ZXJuYWxkaXJlY3Rvcnk=, "src": source, "updated_date": 2013-02-28T11:57:51.000000}
}, cause: Code: 6, Message: Cannot parse string '2013-02-28T11:57:51.000000' as DateTime: syntax error at position 19 (parsed just '2013-02-28T11:57:51'): while executing 'FUNCTION if(isNull(_dummy_0) : 3, defaultValueOfTypeName('DateTime') :: 2, _CAST(_dummy_0, 'DateTime') :: 4) -> if(isNull(_dummy_0), defaultValueOfTypeName('DateTime'), _CAST(_dummy_0, 'DateTime')) DateTime : 1': While executing ValuesBlockInputFormat

**Comment by shubham19may** [comment]
@zzwy2018  please add  http://clickhouse:80?`date_time_input_format=best_effort` in your destination

**Comment by zzwy2018** [comment]
@shubham19may Resolved. Thanks a lot!
