### ISSUE TITLE
Add dynamic variables support into clickhouse raw_statement

### ISSUE THREAD

**Issue by everythings-gonna-be-alright** [jitsucom/jitsu#987]
https://github.com/jitsucom/jitsu/blob/51eec52212801c6e86a46cadf53636f9baa823fd/server/adapters/clickhouse.go#L110

I suggest adding dynamic variables support into raw_statement parameter.
Example:
```
raw_statement: ENGINE = ReplicatedReplacingMergeTree('/clickhouse-custom/somestructure/tables/{shard}/$tablename', '{replica}', _timestamp) PARTITION BY toYYYYMM(_timestamp) ORDER BY (_timestamp)
```
Where $tablename - dynamic tablename

**Comment by vklimontovich** [comment]
Is is something you can avoid by creating tables manually ahead of time? If you can tell us more about your use-case, it would be helpfull.

We didn't design statement templates feature as a universal solution. It's designed to work for simple use-cases, and more sophisticated users should create tables manually ahead of time

**Comment by everythings-gonna-be-alright** [comment]
Not Actual
