### ISSUE TITLE
table names and columns are only being created as lowercase on db

### ISSUE THREAD

**Issue by adisasinani** [jitsucom/jitsu#988]
## Environment

- **Deploy method**: for instance `jitsucom/server docker` 

## Description
When the data is sent to a specific MySQL destination, the table names and columns are created as all lowercase, despite the fact that I have specified otherwise in the configuration. Is it possible to change this?

**Comment by vklimontovich** [comment]
Jitsu transforms all fields from `camelCase` to `camel_case` before putting it to db, at this moment we don't have plan to make it configurable
