### ISSUE TITLE
Interpreted increment sync job does not save the curser position.

### ISSUE THREAD

**Issue by pionoor** [jitsucom/jitsu#991]
## Environment

- **Deploy method**:  `docker-compose.yml`
- **Jitsu version**: `Jitsu 1.43.3`
- **OS**: for instance `Mac OS Ventura 13.1 `

## Description
I have large data that I wanted to move from Snowflake to Clickhouse. While its streaming sometimes it error out and stop the job which is not the main concern for this bug report. The problem is that when do `Run once again` it stream starts all over and produce duplicate event in the destination instead of using the curser pick it up from the last streamed event. 

## Steps to reproduce

If you interrupt increment sync job, and run it once again, it does not use the curser info.

## Expected behavior

If a increment sync job is interpreted for whatever reason, if it gets run again it should resume from the last event was streamed.

**Comment by absorbb** [comment]
Hi @pionoor 
We use Airbyte implementation of Snowflake source. Not sure we can save state on errors without significant rework.

Also Clickhouse supports external table engines https://clickhouse.com/docs/en/engines/table-engines/integrations/. It doesn't support snowflake driver out of the box, but JDBC or ODBC driver can be used instead.
Using external table engine you can setup some cron job that updates clickhouse table directly from showflake table.
Have you considered this approach?
