### ISSUE TITLE
JavaScript transformations no use on postgres -> postgres

### ISSUE THREAD

**Issue by pangafu** [jitsucom/jitsu#993]
## Environment

- **Deploy method**:  `docker-compose.yml` 
- **Jitsu version**:  for instance `1.43.3`
- **OS**: `Ubuntu 20.04
- **Cloud Provider**: 
- **Docker Params (if deployed with docker)**: 

## Description
1. I want to change table name from postgres to postgres, so I use javascript transform in destination database with code

          return { ...$, JITSU_TABLE_NAME: "new_events" }

![image](https://user-images.githubusercontent.com/10149168/213132781-13f2cd22-34f8-4c91-a6c8-2675b05ce068.png)

Old table name is "directus_migrations", I don't see table change to "new_events", still "postgres_directus_migrations"

![image](https://user-images.githubusercontent.com/10149168/213131587-30844afa-ace7-4246-ab1f-4f3b12a43a47.png)

2. Can I keep the field struct with old table and old table name? I find table filed append many columns like "source_id", "src" ...., and filed column sort is out of order

old table struct
![image](https://user-images.githubusercontent.com/10149168/213132221-6657e086-1c57-487d-a302-de96518f2293.png)

changed table struct
![image](https://user-images.githubusercontent.com/10149168/213132316-155dc2c5-6b21-468e-9e5b-29bd5e81000c.png)

3. Can I log the  javascript transform logs into jitsu logs? I use 

        console.log($)

in javascript, it can't output anything to  jitsu logs, only can use in javascript transform debug windows.

**Comment by vklimontovich** [comment]
@pangafu thanks for reporting this. What is the source of the data?

**Comment by absorbb** [comment]
HI @pangafu 

Transformation doesn't work by default for Sources data.
It is still experimental and requires `EXPERIMENTAL_SOURCE_TRANSFORM_ENABLED=true` env variable (or `experimental.source_transform_enabled: true` yaml property)
But due to its early nature:
1. Changing table name for Source data not implemented yet.
2. Removing these columns is not possible. Sort order is correct. It is `_` symbol goes before letters.

3. That is possible. Can you please create an extra ticket for that?

**Comment by pangafu** [comment]
@absorbb 
Thanks for you reply~
1. So how to remapping the "postgre to postgre" 's table name and filed name

2. The sort of field columns can be like old table sort? and make the append filed column by jitsu to last, just like airbytes does. (all column by jitsu append _jitsu_ prefix)

![image](https://user-images.githubusercontent.com/10149168/213338184-3894b4d6-ca76-4b34-9094-5d707a52604f.png)

3. I open a  new feature ticket for "log"

**Comment by pangafu** [comment]
> @pangafu thanks for reporting this. What is the source of the data?

Source database is Postgre, and Dest database is another Postgre

**Comment by naveenseerangan** [comment]
> Same problem happening for me redis(Source) to postgres(destination)

**Comment by vklimontovich** [comment]
Closing. Feel free to reopen if it can be reproduced in Jitsu Next
