### ISSUE TITLE
React-native integration error

### ISSUE THREAD

**Issue by herkoss** [jitsucom/jitsu#996]
## Environment
- **@jitsu/sdk-js**: 3.1.3
- **react-native**: 0.70.6

## Description
I’m trying to add `@jitsu/sdk-js` to `react-native` app, but got error: `TypeError: undefined is not an object (evaluating 'window.location.hostname'`
I realized that Jitsu uses global `window` object, which is different in `react` and `react-native`
Is it possible to add Jitsu in `react-native` app?

## Actual behavior
<img width="493" alt="Screenshot 2023-01-26 at 19 30 52" src="https://user-images.githubusercontent.com/61412282/214909208-cd9e85c4-8004-4909-9515-803988456849.png">

**Comment by vklimontovich** [comment]
Please update `@jitsu/sdk-js` to `3.1.5`, it should be fixed
