### ISSUE TITLE
Change default destination table for all streams from an Airbyte source

### ISSUE THREAD

**Issue by icychocolate98** [jitsucom/jitsu#999]
Good afternoon!

I'm trying to configure Prestashop source. I want to write each table in another custom tables that differs from original one, trying to use each subject + any string. I was searching and I found that maybe using JITSU_TABLE_NAME but I'm not able to map it on destination table.

Instead of writing on "prestashop_customers", I want Jitsu to write on "prestashop_customers_first"  ( and this, with all Prestashop streams ) for example.

I'm also trying something like this in JS debugger:
• `return {...$, in_table: $.JITSU_TABLE_NAME }` to add a field in_table and use that field later in table template like this : `$.in_table}}_in`
Thank you in advice!

[Slack Message](https://jitsuhq.slack.com/archives/C018G6W0URG/p1675955694126859)

**Comment by vklimontovich** [comment]
For transformations on source, you'll need to enable it (starting from [1.43.3](https://github.com/jitsucom/jitsu/releases/tag/v1.43.3)):

```
EXPERIMENTAL_SOURCE_TRANSFORM_ENABLED=true
```

**Comment by absorbb** [comment]
@vklimontovich 
yes. but table mapping doesn't work in transformation for sources.
Will look at what we can do about it.

**Comment by absorbb** [comment]
@icychocolate98 
It is really hard to do right with current design of source sync.
Sources sync is not just plain event flow, it has full-sync or incremental mode and for some sources it works with date intervals that needs to be reprocessed. With that design our flow needs to know in advance what table it works with - to clean it properly or delete data for specific date interval.

What is possible without rewriting sources sync pipleline from scratch:

**1. table names mapping** 
plain one to one table names mapping. without ability to map events from a single collections to multiple db tables, or event multiplication.

**2. convert source data to apiKey stream workaround**
it is theoretically possible to allow syncing sources to webhook destinations.
that webhook can target jitsu api key endpoint
with this approach everything  will be possible regarding data transformation and multiplication
but it won't be possible to clean destination tables from previous data (as sources do in some modes)
and to avoid data duplication it will be required for some column in source collections to contain unique values that may be used as a primary key
and yes that is more like workaround than properly designed feature

Can you please comment on both approach.
We still need to discuss internally whether any of this approaches fit current design.

**Comment by icychocolate98** [comment]
Hi again!

About first point ("1. table names mapping"), where can I map one to one table names ? Maybe editing something where source_table is defined or something like this ?

I was wondering in something like creating new name by appending for example stream name + any stgring ?

It's not a big problem, I could use default destination tables without my nomenclature, it was only to square it in my database structure. But I could use default tables as "in" tables and that's all.

Thank you for your responses!

**Comment by absorbb** [comment]
@icychocolate98 
> where can I map one to one table names ? 

i guess in Streams tab - it is possible to add field for table name for each stream. Will be filled with default table name initially.

**Comment by icychocolate98** [comment]
@absorbb 

Hi! I can't find nothing to add table_name for each stream in 'Streams' tab.

**Comment by saadhypng** [comment]
@absorbb The workaround that you mentioned above to for a source to target the Jitsu API endpoint via a webhook, I was trying to configure it but webhook destinations are not supported for sources. How do you suggest we go about it ? 

![image](https://user-images.githubusercontent.com/88059697/219033841-83b5ae41-3db9-4720-b6db-4e169cbdd276.png)

The goal here is to set a stream in an incremental sync mode, send each updated row to Jitsu API endpoint, transform the data and save in the relevant table. 

Thanks

**Comment by saadhypng** [comment]
Oh, I get it. So for us, solution 2 would work fine, as we don't need to clean the destinations table, the source in question already has a field on which the cursor can be set up for incremental sync if we can get these events to a normal API key flow we can easily send them to the relevant tables. 

in the ideal case scenario, each row read from a stream in a source if can get into a transform directly and can allow table name mapping also that can be ideal, but if it affects other flows I think the above solution is something that can be worked with. 
This has been a major bottle neck in our implementation so if this is something that can be prioritized it will be amazing. Thank you for all the hard work..

**Comment by icychocolate98** [comment]
@saadhypng 

I think that I have configured in a previous project something related to yours.

I use jitsu configurator API to receive multiple events and each event containing a field "event_type". Then, I configured destination table with something like this :
![image](https://user-images.githubusercontent.com/45860726/219093060-058aba36-4dfd-4d03-a81a-cb5a9e368bcb.png)

So, when an event (json) that contains field "event_type" is mapped directly to table custom_data_EVENT_TYPE_in.

I want to perform the same but using Airbyte source like Prestashop, for example, so I cannot add a new custom field called event_type.
I would love the first change but I can work using default airbyte source tables. That's not supposing a problem for me.

**Comment by saadhypng** [comment]
@icychocolate98 Yes I also have a similar setup and it works fine for events coming to the events API, but for airbyte sources its a challenge as webhook destinations are not supported if they are a cool workaround can be to send all read data from streams to a webhook -> ie jitsu events endpoint and then we can use JS transform to easily change tables map data, and skip rows even if wanted. It would solve a big pain for me don't know about the rest. 

I get it is recommended that transformation should be done after load but in our case we don't need to save all the data and also need mapping to standardized as there is a central table rather then separate tables for each sources.

**Comment by saadhypng** [comment]
@absorbb Is there any progress on this, or any estimated timeline to implement webhook-like event streaming for airbyte sources? 

Thank you
